kubedb/installer

chart/kubedb-catalog/Chart.yaml, chart/kubedb/Chart.yaml, chart/kubedb/README.md, deploy/kubedb.sh
=> Fix script path for installer repo

chart/kubedb/templates/cluster-role.yaml, deploy/rbac-list.yaml
xref: https://github.com/kubedb/installer/pull/5/files#diff-83560bf82c859d7e6f8ac8cfbc257963R135
=> Fix missing rbac rules for PDB

chart/kubedb-catalog/templates/mongodb.yaml, deploy/kubedb-catalog/mongodb.yaml
xref: https://github.com/kubedb/project/issues/509
xref: https://github.com/kubedb/project/issues/626
=> Use percona mongodb exporter from 0.13.0

deploy/kubedb.sh
=> Download onessl version v0.13.1 for Kubernetes 1.16 fix

deploy/kubedb-catalog/elasticsearch.yaml
Related to https://github.com/kubedb/elasticsearch/pull/268
Added crd for elasticsearch v7.2.0
=> Add crd for elasticsearch 7.2.0

chart/kubedb-catalog/templates/elasticsearch.yaml, deploy/kubedb-catalog/elasticsearch.yaml
=> Support for xpack in es6.8 and es7.2

chart/kubedb-catalog/templates/postgres.yaml, deploy/kubedb-catalog/postgres.yaml
Xref:
- https://github.com/kubedb/postgres/pull/292
- https://github.com/kubedb/postgres/pull/295/files
=> Update postgres versions

deploy/operator.yaml
=> Ensure operator service points to its own pod.

deploy/kubedb-catalog/elasticsearch.yaml, deploy/kubedb-catalog/etcd.yaml, deploy/kubedb-catalog/memcached.yaml, deploy/kubedb-catalog/mongodb.yaml, deploy/kubedb-catalog/mysql.yaml, deploy/kubedb-catalog/pgbouncer.yaml, deploy/kubedb-catalog/postgres.yaml, deploy/kubedb-catalog/redis.yaml, deploy/kubedb.sh
=> Use separate docker registry for operator and catalog images

deploy/kubedb.sh
xref: https://github.com/kubernetes/kubernetes/issues/85332
=> Properly handle empty image pull secret name in installer

.github/workflows/ci.yml
=> Use kind v0.6.1

charts/kubedb/README.md, charts/kubedb/templates/apiregistration.yaml, charts/kubedb/templates/appcatalog-user-roles.yaml, charts/kubedb/templates/cluster-role-binding.yaml, charts/kubedb/templates/cluster-role.yaml, charts/kubedb/templates/deployment.yaml, charts/kubedb/templates/user-roles.yaml, charts/kubedb/values.yaml, deploy/kubedb.sh, deploy/operator.yaml
=> Always create rbac resources

.github/workflows/ci.yml, Makefile, charts/kubedb-catalog/templates/etcd.yaml, charts/kubedb/templates/cleaner.yaml, charts/kubedb/templates/cluster-role.yaml
=> Use helmpack/chart-testing:v3.0.0-beta.1

charts/kubedb-catalog/templates/percona-xtradb.yaml, charts/kubedb-catalog/templates/proxysql.yaml, charts/kubedb/templates/mutating-webhook.yaml, charts/kubedb/templates/validating-webhook.yaml
=> Conditionally create validating and mutating webhooks.

charts/kubedb/templates/apiregistration.yaml
=> Avoid creating apiservices when webhooks are disabled

charts/kubedb/README.md, charts/kubedb/templates/deployment.yaml, charts/kubedb/templates/mutating-webhook.yaml, charts/kubedb/templates/validating-webhook.yaml
=> Change minimum k8s req to 1.12 and use helm 3 in chart readme

charts/kubedb-catalog/templates/elasticsearch-psp.yaml, charts/kubedb-catalog/templates/memcached-psp.yaml, charts/kubedb-catalog/templates/mongodb-psp.yaml, charts/kubedb-catalog/templates/mysql-psp.yaml, charts/kubedb-catalog/templates/postgres-psp.yaml, charts/kubedb-catalog/templates/redis-psp.yaml
=> Don't install PSP policy when catalog is disabled.

charts/kubedb/templates/cluster-role.yaml, charts/kubedb/templates/mutating-webhook.yaml, charts/kubedb/templates/validating-webhook.yaml
=> Add missing permissions for PgBouncer operator

charts/kubedb-catalog/templates/elasticsearch.yaml, charts/kubedb-catalog/templates/mongodb.yaml, charts/kubedb-catalog/templates/mysql.yaml, charts/kubedb-catalog/templates/postgres.yaml, charts/kubedb/templates/cluster-role.yaml
xref: https://github.com/kubedb/mongodb/pull/183
=> Add deletocollection verbs to kubedb roles

charts/kubedb/templates/deployment.yaml, charts/kubedb/templates/service.yaml, charts/kubedb/templates/servicemonitor.yaml, charts/kubedb/values.yaml
=> Add enterprise operator sidecar

.github/workflows/ci.yml
=> Run checks once in CI pipeline

charts/kubedb-catalog/templates/mongodb.yaml
Signed-off-by: the-redback <maruf@appscode.com>
=> Updated Mongodb Init images

charts/kubedb/templates/user-roles.yaml
=> Update user roles for KubeDB crds

.github/workflows/ci.yml
ref: https://github.com/kubernetes/kubernetes/issues/90074
=> Use kubectl v1.17.0

apis/installer/fuzzer/fuzzer.go, apis/installer/install/pruning_test.go, apis/installer/v1alpha1/register.go
=> Add fuzz tests for CRDs

.github/workflows/ci.yml, .github/workflows/release.yml
=> Use GCR_SERVICE_ACCOUNT_JSON_KEY env in CI

.github/workflows/ci.yml, Makefile, charts/kubedb-catalog/README.md, charts/kubedb-catalog/doc.yaml, charts/kubedb-catalog/values.yaml, charts/kubedb/README.md, charts/kubedb/doc.yaml, charts/kubedb/values.yaml
=> Auto generate chart readme file

charts/kubedb-catalog/templates/elasticsearch-psp.yaml, charts/kubedb-catalog/templates/mongodb-psp.yaml, charts/kubedb-catalog/templates/mysql-psp.yaml, charts/kubedb-catalog/templates/postgres-psp.yaml
Signed-off-by: hossainemruz <emruz@appscode.com>
=> Remove PSP for Snapshot

charts/kubedb/templates/cluster-role-enterprise.yaml, charts/kubedb/templates/user-roles.yaml
=> Rename api group to ops.kubedb.com

.github/workflows/ci.yml, Makefile, charts/kubedb/values.yaml
=> Update enterprise operator tag

charts/kubedb/templates/cluster-role.yaml
xref: https://github.com/kubernetes/kubernetes/pull/85004
=> Permit configmap list/watch for delegated authentication

charts/kubedb/templates/cluster-role.yaml, charts/kubedb/templates/gerbage-collector-rbac.yaml
Signed-off-by: hossainemruz <emruz@appscode.com>
=> Add RBAC permission for generic garbage collector

.github/workflows/ci.yml, charts/kubedb-enterprise/templates/apiregistration.yaml, charts/kubedb-enterprise/templates/cleaner.yaml, charts/kubedb-enterprise/templates/mutating-webhook.yaml, charts/kubedb-enterprise/templates/validating-webhook.yaml, charts/kubedb/templates/mutating-webhook.yaml, charts/kubedb/templates/validating-webhook.yaml
=> Revise the validator & mutator webhook names

charts/kubedb-catalog/templates/pgbouncer/pgbouncer-1.10.0.yaml, charts/kubedb-catalog/templates/pgbouncer/pgbouncer-1.11.0.yaml, charts/kubedb-catalog/templates/pgbouncer/pgbouncer-1.12.0.yaml, charts/kubedb-catalog/templates/pgbouncer/pgbouncer-1.7.1.yaml, charts/kubedb-catalog/templates/pgbouncer/pgbouncer-1.7.2.yaml, charts/kubedb-catalog/templates/pgbouncer/pgbouncer-1.7.yaml, charts/kubedb-catalog/templates/pgbouncer/pgbouncer-1.8.1.yaml, charts/kubedb-catalog/templates/pgbouncer/pgbouncer-1.9.0.yaml
=> Remove default deprecated: false fields

charts/kubedb-catalog/templates/postgres/postgres-9.6.yaml
=> Bring back postgres 9.6

Makefile, charts/kubedb-catalog/Chart.yaml, charts/kubedb-enterprise/Chart.yaml, charts/kubedb-enterprise/values.yaml, charts/kubedb/Chart.yaml, charts/kubedb/values.yaml, lintconf.yaml
=> Add commands to update chart

charts/kubedb-catalog/templates/mysql/mysql-5.7.25.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.29.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.14.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.18.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.19.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.20.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.3.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.yaml
=> Update MySQL version catalog

charts/kubedb-catalog/templates/mongodb/percona-3.6.18.yaml, charts/kubedb-catalog/templates/mongodb/percona-4.0.10.yaml, charts/kubedb-catalog/templates/mongodb/percona-4.2.7.yaml
=> Use `percona` as Suffix in MongoDBVersion Name

charts/kubedb-enterprise/templates/cluster-role.yaml
Signed-off-by: anis028 <anis028@appscode.com>
=> Add Pod `exec` permission in ClusterRole

charts/kubedb-catalog/templates/redis/redis-6.0.5.yaml, charts/kubedb-catalog/templates/redis/redis-6.0.6.yaml, charts/kubedb/templates/cluster-role.yaml
=> Add support for Redis 6.0.6

charts/kubedb-enterprise/templates/cluster-role.yaml, charts/kubedb/templates/cluster-role.yaml
=> Remove excess permission

charts/kubedb-catalog/templates/mysql/mysql-5.7.25.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.29.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.31.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.14.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.20.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.21.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.3.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.yaml
Todo:
Signed-off-by: suaas21 <sagor@appscode.com>
=> Add MySQL New catalog 

charts/kubedb-catalog/templates/elasticsearch/7.9.1-xpack.yaml
=> Add support for elasticsearch version 7.9.1-xpack

charts/kubedb/templates/cluster-role.yaml
Signed-off-by: Emruz Hossain <emruz@appscode.com>
This bug was introduced by: #134
=> Fix RBAC for Stash

charts/kubedb-catalog/templates/elasticsearch/1.0.2-opendistro.yaml, charts/kubedb-catalog/templates/elasticsearch/1.1.0-opendistro.yaml, charts/kubedb-catalog/templates/elasticsearch/1.2.1-opendistro.yaml, charts/kubedb-catalog/templates/elasticsearch/1.3.0-opendistro.yaml, charts/kubedb-catalog/templates/elasticsearch/1.4.0-opendistro.yaml, charts/kubedb-catalog/templates/elasticsearch/1.6.0-opendistro.yaml, charts/kubedb-catalog/templates/elasticsearch/1.7.0-opendistro.yaml, charts/kubedb-catalog/templates/elasticsearch/1.8.0-opendistro.yaml, charts/kubedb-catalog/templates/elasticsearch/1.9.0-opendistro.yaml, charts/kubedb-catalog/templates/elasticsearch/6.8.1-searchguard.yaml, charts/kubedb-catalog/templates/elasticsearch/6.8.10-xpack.yaml, charts/kubedb-catalog/templates/elasticsearch/7.0.1-searchguard.yaml, charts/kubedb-catalog/templates/elasticsearch/7.0.1-xpack.yaml, charts/kubedb-catalog/templates/elasticsearch/7.1.1-searchguard.yaml, charts/kubedb-catalog/templates/elasticsearch/7.1.1-xpack.yaml, charts/kubedb-catalog/templates/elasticsearch/7.2.1-xpack.yaml, charts/kubedb-catalog/templates/elasticsearch/7.3.2-xpack.yaml, charts/kubedb-catalog/templates/elasticsearch/7.4.2-xpack.yaml, charts/kubedb-catalog/templates/elasticsearch/7.5.2-searchguard.yaml, charts/kubedb-catalog/templates/elasticsearch/7.5.2-xpack.yaml, charts/kubedb-catalog/templates/elasticsearch/7.6.2-xpack.yaml, charts/kubedb-catalog/templates/elasticsearch/7.7.1-xpack.yaml, charts/kubedb-catalog/templates/elasticsearch/7.8.0-xpack.yaml, charts/kubedb-catalog/templates/elasticsearch/7.9.1-xpack.yaml
=> Update elasticsearch-init images

go.mod, go.sum, vendor/github.com/coreos/pkg/capnslog/init.go, vendor/kmodules.xyz/client-go/go.sum, vendor/modules.txt
=> Update KubeDB api

charts/kubedb-enterprise/templates/cluster-role.yaml
=> Add permission to update cert-manager certificates status

charts/kubedb/templates/cluster-role.yaml
=> Add StatefulSet watch permission

charts/kubedb-enterprise/templates/servicemonitor.yaml, charts/kubedb/templates/servicemonitor.yaml
=> Remove caFile from ServiceMonitor

go.mod, go.sum, vendor/github.com/coreos/pkg/capnslog/init.go, vendor/modules.txt
=> Update Kubernetes v1.18.9 dependencies

charts/kubedb-catalog/templates/mongodb/mongodb-3.4.17.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.4.22.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.13.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.8.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.11.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.3.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.5.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.13.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.4.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.7.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.2.3.yaml, charts/kubedb-catalog/templates/mongodb/percona-3.6.18.yaml, charts/kubedb-catalog/templates/mongodb/percona-4.0.10.yaml, charts/kubedb-catalog/templates/mongodb/percona-4.2.7.yaml
=> Update mongodb-init container versions

go.mod, go.sum, hack/gencrd/main.go, vendor/gomodules.xyz/runtime/LICENSE, vendor/gomodules.xyz/runtime/README.md, vendor/gomodules.xyz/runtime/go.mod, vendor/gomodules.xyz/runtime/runtime.go, vendor/modules.txt
=> Replace appscode/go with gomodules.xyz/x

charts/kubedb-enterprise/templates/cluster-role.yaml
=> Add permissions to evict pods

charts/kubedb-catalog/templates/mongodb/mongodb-3.4.17.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.4.22.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.13.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.8.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.11.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.3.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.5.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.13.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.4.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.7.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.2.3.yaml, charts/kubedb-catalog/templates/mongodb/percona-3.6.18.yaml, charts/kubedb-catalog/templates/mongodb/percona-4.0.10.yaml, charts/kubedb-catalog/templates/mongodb/percona-4.2.7.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-5.7.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-5.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-8.0.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-8.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.25.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.29.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.31.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.14.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.20.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.21.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.3.yaml
=> Add `ReplicationModeDetector` Image for MongoDB

charts/kubedb/templates/NOTES.txt
=> Update NOTE.txt with helm 3 command

charts/kubedb-enterprise/templates/apiregistration.yaml, charts/kubedb/templates/apiregistration.yaml
=> Use apiregistration.k8s.io/v1

charts/kubedb-catalog/templates/mongodb/percona-3.6.18.yaml, charts/kubedb-catalog/templates/mongodb/percona-4.0.10.yaml, charts/kubedb-catalog/templates/mongodb/percona-4.2.7.yaml
=> Update Percona MongoDB Server Images

charts/kubedb/templates/cluster-role.yaml
=> Add permission to update pod status

charts/kubedb/templates/cluster-role.yaml
=> Add permissions for updating pod status

.github/workflows/ci.yml
=> Cleanup CI workflow

charts/kubedb-autoscaler/templates/cluster-role.yaml, charts/kubedb-enterprise/templates/cluster-role.yaml, charts/kubedb/templates/cluster-role.yaml
This is an extension of PR #226 and fixes an issue where the operator is
trying to set a owner reference on a PDB
=> Add statefulsets/finalizers to ClusterRole

.github/workflows/ci.yml, .gitignore, charts/kubedb-catalog/templates/mariadb/mariadb-10.4.17.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.5.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-psp.yaml, charts/kubedb/templates/cluster-role.yaml, charts/kubedb/templates/mutating-webhook.yaml, charts/kubedb/templates/validating-webhook.yaml
Added:
Signed-off-by: Alif Biswas <alif@appscode.com>
=> Add MariaDB Catalogs

charts/kubedb-autoscaler/README.md, charts/kubedb-catalog/README.md, charts/kubedb-community/README.md, charts/kubedb-crds/README.md, charts/kubedb-enterprise/README.md, charts/kubedb/.helmignore, charts/kubedb/Chart.yaml, charts/kubedb/README.md, charts/kubedb/doc.yaml, charts/kubedb/templates/NOTES.txt, charts/kubedb/templates/_helpers.tpl, charts/kubedb/values.yaml
=> Add combined kubedb chart

charts/kubedb-crds/crds/kubedb.com_mysqls.yaml
=> Update crds for kubedb/apimachinery@5b44aa8c

charts/kubedb-crds/crds/catalog.kubedb.com_elasticsearchversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_etcdversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mongodbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mysqlversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_perconaxtradbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_postgresversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_redisversions.yaml
=> Update crds for kubedb/apimachinery@612f7384

charts/kubedb-crds/crds/catalog.kubedb.com_elasticsearchversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_etcdversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mongodbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mysqlversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_perconaxtradbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_postgresversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_redisversions.yaml
=> Update crds for kubedb/apimachinery@1b8ec75a

charts/kubedb-crds/crds/ops.kubedb.com_mysqlopsrequests.yaml
=> Update crds for kubedb/apimachinery@f4aa5bcc

charts/kubedb-crds/crds/catalog.kubedb.com_etcdversions.yaml
=> Update crds for kubedb/apimachinery@169675bb

apis/installer/v1alpha1/kubedb_catalog_types.go, charts/kubedb-catalog/README.md, charts/kubedb-catalog/templates/mongodb/deprecated-mongodb-3.4.yaml, charts/kubedb-catalog/templates/mongodb/deprecated-mongodb-3.6.yaml, charts/kubedb-catalog/templates/mongodb/deprecated-mongodb-4.0.yaml, charts/kubedb-catalog/templates/mongodb/deprecated-mongodb-4.1.yaml, charts/kubedb-catalog/templates/mongodb/deprecated-mongodb-4.2.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.4.17.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.4.22.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.13.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.8.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.11.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.3.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.5.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.13.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.4.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.7.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.2.3.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-psp.yaml, charts/kubedb-catalog/templates/mongodb/percona-3.6.18.yaml, charts/kubedb-catalog/templates/mongodb/percona-4.0.10.yaml, charts/kubedb-catalog/templates/mongodb/percona-4.2.7.yaml, charts/kubedb-catalog/values.openapiv3_schema.yaml, charts/kubedb-catalog/values.yaml, crds/installer.kubedb.com_kubedbcatalogs.yaml, go.sum
=> .Values.catalog.mongo -> .Values.catalog.mongodb

charts/kubedb-crds/crds/catalog.kubedb.com_elasticsearchversions.yaml
=> Update crds for kubedb/apimachinery@5e28f585

hack/scripts/import-crds.sh
=> Add import-crds.sh script

charts/kubedb-autoscaler/templates/deployment.yaml, charts/kubedb-community/templates/deployment.yaml, charts/kubedb-enterprise/templates/deployment.yaml
=> Add temporary volume for storing temporary certificates

catalog/raw/postgres/postgres-10.16-postgresql.yaml, catalog/raw/postgres/postgres-11.11-postgresql.yaml, catalog/raw/postgres/postgres-12.6-postgresql.yaml, catalog/raw/postgres/postgres-13.2-postgresql.yaml, catalog/raw/postgres/postgres-9.6.21-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-10.16-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.11-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.6-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.2-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-9.6.21-postgresql.yaml
fix: updated db image with official postgres image
=> Added official image for postgres

go.mod, go.sum, hack/fmt/main.go, vendor/gomodules.xyz/semvers/lib.go, vendor/modules.txt, vendor/stash.appscode.dev/catalog/go.mod, vendor/stash.appscode.dev/catalog/go.sum, vendor/stash.appscode.dev/catalog/types.go
=> Handle non-semver db version names

catalog/active_versions.json, catalog/backup_tasks.json, catalog/raw/postgres/postgres-11.11-timescaledb.yaml, catalog/raw/postgres/postgres-12.6-timescaledb.yaml, catalog/raw/postgres/postgres-13.2-timescaledb.yaml, catalog/restore_tasks.json, charts/kubedb-catalog/templates/postgres/postgres-11.11-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.6-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.2-timescaledb.yaml
=> Add TimescaleDB in Postgres catalog

catalog/raw/postgres/postgres-11.11-timescaledb.yaml, catalog/raw/postgres/postgres-12.6-timescaledb.yaml, catalog/raw/postgres/postgres-13.2-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.11-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.6-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.2-timescaledb.yaml
Fix: Add open source images for TimescaleDB
=> Add open source images for TimescaleDB

charts/kubedb-enterprise/templates/validating-webhook.yaml
=> Add MongoDBOpsRequest Validator

charts/kubedb-enterprise/templates/validating-webhook.yaml
=> Add Elasticsearch and Redis OpsRequest Validator

charts/kubedb-autoscaler/templates/cleaner.yaml, charts/kubedb-community/templates/cleaner.yaml, charts/kubedb-enterprise/templates/cleaner.yaml
=> Use different cleaner name

catalog/active_versions.json, catalog/backup_tasks.json, catalog/raw/postgres/postgres-10.16-postgresql.yaml, catalog/raw/postgres/postgres-11.11-postgresql.yaml, catalog/raw/postgres/postgres-11.11-timescaledb.yaml, catalog/raw/postgres/postgres-12.6-postgresql.yaml, catalog/raw/postgres/postgres-12.6-timescaledb.yaml, catalog/raw/postgres/postgres-13.2-postgresql.yaml, catalog/raw/postgres/postgres-13.2-timescaledb.yaml, catalog/raw/postgres/postgres-9.6.21-postgresql.yaml, catalog/restore_tasks.json, charts/kubedb-catalog/crds/catalog.kubedb.com_postgresversions.yaml, charts/kubedb-catalog/templates/postgres/postgres-10.16-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.11-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.11-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.6-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.6-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.2-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.2-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-9.6.21-postgresql.yaml
=> Custom UID for Postgres

catalog/raw/mariadb/mariadb-10.4.17.yaml, catalog/raw/mariadb/mariadb-10.5.8.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.4.17.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.5.8.yaml
=> Add mariadb-init-docker Image

charts/kubedb-enterprise/templates/cluster-role.yaml
=> Add `poddisruptionbudgets` and backup permissions for KubeDB Enterprise

catalog/raw/mongodb/mongodb-3.4.17-mongodb.yaml, catalog/raw/mongodb/mongodb-3.4.22-mongodb.yaml, catalog/raw/mongodb/mongodb-3.6.13-mongodb.yaml, catalog/raw/mongodb/mongodb-3.6.18-percona.yaml, catalog/raw/mongodb/mongodb-3.6.8-mongodb.yaml, catalog/raw/mongodb/mongodb-4.0.10-percona.yaml, catalog/raw/mongodb/mongodb-4.0.11-mongodb.yaml, catalog/raw/mongodb/mongodb-4.0.3-mongodb.yaml, catalog/raw/mongodb/mongodb-4.0.5-mongodb.yaml, catalog/raw/mongodb/mongodb-4.1.13-mongodb.yaml, catalog/raw/mongodb/mongodb-4.1.4-mongodb.yaml, catalog/raw/mongodb/mongodb-4.1.7-mongodb.yaml, catalog/raw/mongodb/mongodb-4.2.3-mongodb.yaml, catalog/raw/mongodb/mongodb-4.2.7-percona.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.4.17-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.4.22-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.13-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.18-percona.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.8-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.10-percona.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.11-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.3-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.5-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.13-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.4-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.7-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.2.3-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.2.7-percona.yaml
=> Update MongoDB init container image

catalog/raw/mongodb/mongodb-3.4.17-mongodb.yaml, catalog/raw/mongodb/mongodb-3.4.22-mongodb.yaml, catalog/raw/mongodb/mongodb-3.6.13-mongodb.yaml, catalog/raw/mongodb/mongodb-3.6.18-percona.yaml, catalog/raw/mongodb/mongodb-3.6.8-mongodb.yaml, catalog/raw/mongodb/mongodb-4.0.10-percona.yaml, catalog/raw/mongodb/mongodb-4.0.11-mongodb.yaml, catalog/raw/mongodb/mongodb-4.0.3-mongodb.yaml, catalog/raw/mongodb/mongodb-4.0.5-mongodb.yaml, catalog/raw/mongodb/mongodb-4.1.13-mongodb.yaml, catalog/raw/mongodb/mongodb-4.1.4-mongodb.yaml, catalog/raw/mongodb/mongodb-4.1.7-mongodb.yaml, catalog/raw/mongodb/mongodb-4.2.3-mongodb.yaml, catalog/raw/mongodb/mongodb-4.2.7-percona.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.4.17-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.4.22-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.13-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.18-percona.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.8-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.10-percona.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.11-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.3-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.5-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.13-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.4-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.7-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.2.3-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.2.7-percona.yaml
=> Use mongodb-exporter v0.20.4

catalog/raw/postgres/postgres-10.16-postgresql.yaml, catalog/raw/postgres/postgres-11.11-postgresql.yaml, catalog/raw/postgres/postgres-11.11-timescaledb.yaml, catalog/raw/postgres/postgres-12.6-postgresql.yaml, catalog/raw/postgres/postgres-12.6-timescaledb.yaml, catalog/raw/postgres/postgres-13.2-postgresql.yaml, catalog/raw/postgres/postgres-13.2-timescaledb.yaml, catalog/raw/postgres/postgres-9.6.21-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-10.16-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.11-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.11-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.6-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.6-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.2-postgresql.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.2-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-9.6.21-postgresql.yaml, charts/kubedb-crds/crds/ops.kubedb.com_postgresopsrequests.yaml
=> Fix: Update Ops Request yaml for Reconfigure TLS in Postgres

catalog/active_versions.json, catalog/backup_tasks.json, catalog/raw/elasticsearch/elasticsearch-7.10.2-searchguard.yaml, catalog/raw/elasticsearch/elasticsearch-7.13.2-elasticstack.yaml, catalog/restore_tasks.json, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-7.10.2-searchguard.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-7.13.2-elasticstack.yaml
=> Add support for Elasticsearch v7.13.2

charts/kubedb-metrics/.helmignore, charts/kubedb-metrics/Chart.yaml, charts/kubedb-metrics/README.md, charts/kubedb-metrics/crds/metrics.appscode.com_metricsconfigurations.yaml, charts/kubedb-metrics/doc.yaml, charts/kubedb-metrics/templates/NOTES.txt, charts/kubedb-metrics/templates/user-roles.yaml, charts/kubedb-metrics/values.yaml, hack/scripts/ct.sh, hack/scripts/import-crds.sh
=> Add kubedb-metrics chart

charts/kubedb-autoscaler/templates/cleaner.yaml, charts/kubedb-community/templates/cleaner.yaml, charts/kubedb-enterprise/templates/cleaner.yaml
=> Pass image pull secrets to cleaner images

.github/workflows/ci.yml, Makefile, charts/kubedb-autoscaler/Chart.yaml, charts/kubedb-autoscaler/doc.yaml, charts/kubedb-autoscaler/values.openapiv3_schema.yaml, charts/kubedb-catalog/Chart.yaml, charts/kubedb-catalog/doc.yaml, charts/kubedb-community/Chart.yaml, charts/kubedb-community/doc.yaml, charts/kubedb-community/values.openapiv3_schema.yaml, charts/kubedb-crds/doc.yaml, charts/kubedb-enterprise/Chart.yaml, charts/kubedb-enterprise/doc.yaml, charts/kubedb-enterprise/values.openapiv3_schema.yaml, charts/kubedb/Chart.yaml, charts/kubedb/doc.yaml, charts/kubedb/values.openapiv3_schema.yaml
=> Update kubedb chart dependencies via Makefile

charts/kubedb-crds/crds/metrics.appscode.com_metricsconfigurations.yaml, charts/kubedb-crds/templates/metricsconfig-kubedb-com-elasticsearch.yaml, charts/kubedb-crds/templates/metricsconfig-kubedb-com-mariadb.yaml, charts/kubedb-crds/templates/metricsconfig-kubedb-com-mongodb.yaml, charts/kubedb-crds/templates/metricsconfig-kubedb-com-mysql.yaml, charts/kubedb-crds/templates/metricsconfig-kubedb-com-postgres.yaml
=> Rename functions in metrics configuration

charts/kubedb-crds/templates/metricsconfig-kubedb-com-redis.yaml
=> Add redis cluster metrics configuration

charts/kubedb-crds/templates/metricsconfig-kubedb-com-mongodb.yaml
=> (WIP) Update MongoDB resource metrics

charts/kubedb-metrics/templates/metricsconfig-kubedb-com-elasticsearch.yaml, charts/kubedb-metrics/templates/metricsconfig-kubedb-com-mariadb.yaml, charts/kubedb-metrics/templates/metricsconfig-kubedb-com-mongodb.yaml, charts/kubedb-metrics/templates/metricsconfig-kubedb-com-mysql.yaml, charts/kubedb-metrics/templates/metricsconfig-kubedb-com-postgres.yaml, charts/kubedb-metrics/templates/metricsconfig-kubedb-com-redis.yaml
=> Fix metrics for resource calculation

catalog/raw/mongodb/mongodb-3.4.17-mongodb.yaml, catalog/raw/mongodb/mongodb-3.4.22-mongodb.yaml, catalog/raw/mongodb/mongodb-3.6.13-mongodb.yaml, catalog/raw/mongodb/mongodb-3.6.8-mongodb.yaml, catalog/raw/mongodb/mongodb-4.0.11-mongodb.yaml, catalog/raw/mongodb/mongodb-4.0.3-mongodb.yaml, catalog/raw/mongodb/mongodb-4.0.5-mongodb.yaml, catalog/raw/mongodb/mongodb-4.1.13-mongodb.yaml, catalog/raw/mongodb/mongodb-4.1.4-mongodb.yaml, catalog/raw/mongodb/mongodb-4.1.7-mongodb.yaml, catalog/raw/mongodb/mongodb-4.2.3-mongodb.yaml, catalog/raw/mongodb/mongodb-4.4.6-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.4.17-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.4.22-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.13-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-3.6.8-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.11-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.3-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.5-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.13-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.4-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.7-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.2.3-mongodb.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.4.6-mongodb.yaml
=> Use mongodb official images

charts/kubedb-catalog/ci/ci-values.yaml
=> Test schema validity for deprecated catalog versions

.github/workflows/ci.yml
=> Check metrics configuration

hack/fmt/main.go
=> Update spec for a given api kind

catalog/raw/mariadb/mariadb-10.4.17.yaml, catalog/raw/mariadb/mariadb-10.5.8.yaml, catalog/raw/mariadb/mariadb-10.6.4.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.4.17.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.5.8.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.6.4.yaml
=> Use kubedb/mariadb-init:0.4.0

catalog/raw/mariadb/mariadb-10.4.17.yaml, catalog/raw/mariadb/mariadb-10.5.8.yaml, catalog/raw/mariadb/mariadb-10.6.4.yaml, catalog/raw/mysql/mysql-5.7.25-oracle.yaml, catalog/raw/mysql/mysql-5.7.29-oracle.yaml, catalog/raw/mysql/mysql-5.7.31-oracle.yaml, catalog/raw/mysql/mysql-5.7.33-oracle.yaml, catalog/raw/mysql/mysql-5.7.35-oracle.yaml, catalog/raw/mysql/mysql-8.0.14-oracle.yaml, catalog/raw/mysql/mysql-8.0.20-oracle.yaml, catalog/raw/mysql/mysql-8.0.21-oracle.yaml, catalog/raw/mysql/mysql-8.0.23-oracle.yaml, catalog/raw/mysql/mysql-8.0.26-oracle.yaml, catalog/raw/mysql/mysql-8.0.3-oracle.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.4.17.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.5.8.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.6.4.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.25-oracle.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.29-oracle.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.31-oracle.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.33-oracle.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.35-oracle.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.14-oracle.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.20-oracle.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.21-oracle.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.23-oracle.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.26-oracle.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.3-oracle.yaml
=> Update mysqld exporter version to v0.13.0

charts/kubedb-autoscaler/templates/cluster-role.yaml, charts/kubedb-autoscaler/templates/operator-psp.yaml, charts/kubedb-community/templates/cluster-role.yaml, charts/kubedb-enterprise/templates/cluster-role.yaml
=> Configure psp for enterprise and autoscaler pods

charts/kubedb-metrics/templates/metricsconfig-catalog-kubedb-com-elasticsearch-version.yaml, charts/kubedb-metrics/templates/metricsconfig-catalog-kubedb-com-mongodb-version.yaml, charts/kubedb-metrics/templates/metricsconfig-catalog-kubedb-com-postgres-version.yaml, charts/kubedb-metrics/templates/metricsconfig-kubedb-com-elasticsearch.yaml
=> Update various kubedb metrics and metric labels

charts/kubedb-metrics/templates/metricsconfig-kubedb-com-redissentinel.yaml
=> Add redis sentinel metrics configuration

catalog/raw/postgres/postgres-10.16-official.yaml, catalog/raw/postgres/postgres-10.18-official.yaml, catalog/raw/postgres/postgres-11.11-official.yaml, catalog/raw/postgres/postgres-11.11-timescaledb.yaml, catalog/raw/postgres/postgres-11.13-official.yaml, catalog/raw/postgres/postgres-12.6-official.yaml, catalog/raw/postgres/postgres-12.6-timescaledb.yaml, catalog/raw/postgres/postgres-12.8-official.yaml, catalog/raw/postgres/postgres-13.2-official.yaml, catalog/raw/postgres/postgres-13.2-timescaledb.yaml, catalog/raw/postgres/postgres-13.4-official.yaml, catalog/raw/postgres/postgres-14.0-official.yaml, catalog/raw/postgres/postgres-9.6.21-official.yaml, catalog/raw/postgres/postgres-9.6.23-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-10.16-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-10.18-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.11-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.11-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.13-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.6-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.6-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.8-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.2-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.2-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.4-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-14.0-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-9.6.21-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-9.6.23-official.yaml
=> Update Postgres-init Image Version to v0.4.0

charts/kubedb-autoscaler/README.md, charts/kubedb-autoscaler/doc.yaml, charts/kubedb-autoscaler/templates/apiregistration.yaml, charts/kubedb-catalog/README.md, charts/kubedb-catalog/doc.yaml, charts/kubedb-community/README.md, charts/kubedb-community/doc.yaml, charts/kubedb-community/templates/apiregistration.yaml, charts/kubedb-community/templates/garbage-collector-rbac.yaml, charts/kubedb-crds/README.md, charts/kubedb-crds/doc.yaml, charts/kubedb-enterprise/README.md, charts/kubedb-enterprise/doc.yaml, charts/kubedb-enterprise/templates/apiregistration.yaml, charts/kubedb-enterprise/templates/gerbage-collector-rbac.yaml, charts/kubedb-metrics/README.md, charts/kubedb-metrics/doc.yaml, charts/kubedb/README.md, charts/kubedb/doc.yaml
=> Change installer namespace to kubedb

charts/kubedb-autoscaler/templates/apiregistration.yaml, charts/kubedb-community/templates/apiregistration.yaml, charts/kubedb-enterprise/templates/apiregistration.yaml
=> Fix regression in #386

charts/kubedb-autoscaler/templates/license-checker-cluster-role-binding.yaml, charts/kubedb-autoscaler/templates/license-reader-cluster-role-binding.yaml, charts/kubedb-autoscaler/templates/license.yaml, charts/kubedb-community/templates/license-checker-cluster-role-binding.yaml, charts/kubedb-community/templates/license-reader-cluster-role-binding.yaml, charts/kubedb-community/templates/license.yaml, charts/kubedb-enterprise/templates/license-checker-cluster-role-binding.yaml, charts/kubedb-enterprise/templates/license-reader-cluster-role-binding.yaml, charts/kubedb-enterprise/templates/license.yaml
=> Add labels to license related rolebindings & secrets

catalog/raw/mysql/mysql-5.7.36-official.yaml, catalog/raw/mysql/mysql-8.0.17-official.yaml, catalog/raw/mysql/mysql-8.0.27-mysql.yaml, catalog/raw/mysql/mysql-8.0.27-official.yaml, catalog/raw/mysql/mysql-8.0.3-official.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.36-official.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.17-official.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.27-mysql.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.27-official.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.3-official.yaml
Signed-off-by: Alif Biswas <alif@appscode.com>
=> Use mysqld Exporter Image with custom query support

charts/kubedb-ui-server/templates/cluster-role.yaml
=> Grant permission to watch rbac resources

.gitignore, charts/kubedb-opscenter/.helmignore, charts/kubedb-opscenter/Chart.lock, charts/kubedb-opscenter/Chart.yaml, charts/kubedb-opscenter/doc.yaml, charts/kubedb-opscenter/templates/_helpers.tpl, charts/kubedb-opscenter/values.yaml, charts/kubedb-ui-server/Chart.yaml, hack/scripts/update-chart-dependencies.sh
=> Add kubedb-opscenter chart

charts/kubedb-opscenter/README.md
=> Update repository config

charts/kubedb-grafana-dashboards/data/resources.yaml, charts/kubedb-grafana-dashboards/templates/dashboard.yaml
=> Add k8s.io/{group,kind,resource} labels to grafana dashboards

charts/kubedb-ops-manager/templates/cluster-role.yaml
=> Add permissions for Reprovision

charts/kubedb-crds/crds/kubedb.com_mongodbs.yaml, charts/kubedb-crds/crds/ops.kubedb.com_elasticsearchopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_etcdopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mariadbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_memcachedopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mongodbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mysqlopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_perconaxtradbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_pgbounceropsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_postgresopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_proxysqlopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_redisopsrequests.yaml, charts/kubedb-grafana-dashboards/README.md, charts/kubedb-grafana-dashboards/crds/openviz.dev_grafanadashboards.yaml, charts/kubedb-grafana-dashboards/templates/dashboard.yaml, charts/kubedb-grafana-dashboards/values.yaml, charts/kubedb-ui-server/crds/kubedb.com_mongodbs.yaml, crds/kubedb-crds.yaml
=> Update Grafana chart

charts/kubedb-grafana-dashboards/templates/dashboard.yaml
=> Correctly generate grafana dashboard name

charts/kubedb-ui-server/templates/cluster-role.yaml
=> Add permission for nonResourceURLs

catalog/raw/mysql/deprecated-mysql-5-official.yaml, catalog/raw/mysql/deprecated-mysql-5.7-official.yaml, catalog/raw/mysql/deprecated-mysql-5.7.25-official.yaml, catalog/raw/mysql/deprecated-mysql-8-official.yaml, catalog/raw/mysql/deprecated-mysql-8.0-official.yaml, catalog/raw/mysql/deprecated-mysql-8.0.14-official.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-5-official.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-5.7-official.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-5.7.25-official.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-8-official.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-8.0-official.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-8.0.14-official.yaml
Signed-off-by: Mehedi Hasan <mehedi.hasan@appscode.com>
=> Update upgradeConstraint for MySQL deprecated versions.

charts/kubedb-schema-manager/templates/cluster-role.yaml
Signed-off-by: Arnob kumar saha <arnob@appscode.com>
=> Add cluster-role for Schemas

charts/kubedb-dashboard/templates/cluster-role.yaml
Signed-off-by: raihankhan <raihan@appscode.com>
=> Add dashboard cluster roles

charts/kubedb-webhook-server/templates/apiregistration.yaml, charts/kubedb-webhook-server/templates/autoscaler/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/dashboard/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/dashboard/validating-webhook.yaml, charts/kubedb-webhook-server/templates/ops-manager/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/ops-manager/validating-webhook.yaml, charts/kubedb-webhook-server/templates/provisioner/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/provisioner/validating-webhook.yaml, charts/kubedb-webhook-server/templates/schema-manager/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/schema-manager/validating-webhook.yaml
=> Allow partially installing webhook server

Makefile, charts/kubedb-dashboard/Chart.yaml, charts/kubedb-schema-manager/Chart.yaml, charts/kubedb-webhook-server/Chart.yaml, charts/kubedb/Chart.lock, charts/kubedb/Chart.yaml
=> Add webhook chart to combined chart

charts/kubedb-webhook-server/templates/apiregistration.yaml, charts/kubedb-webhook-server/templates/schema-manager/validating-webhook.yaml
=> Activate PostgresDatabase validation webhook

charts/kubedb-webhook-server/templates/autoscaler/mutating-webhook.yaml
=> Add MariaDB autoscaler mutator webhook

catalog/raw/redis/deprecated-redis-4.0.yaml, catalog/raw/redis/deprecated-redis-4.yaml, catalog/raw/redis/deprecated-redis-5.0.yaml, catalog/raw/redis/redis-4.0.11.yaml, catalog/raw/redis/redis-4.0.6.yaml, catalog/raw/redis/redis-5.0.3.yaml, catalog/raw/redis/redis-6.0.6.yaml, catalog/raw/redis/redis-6.2.5.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-4.0.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-4.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-5.0.yaml, charts/kubedb-catalog/templates/redis/redis-4.0.11.yaml, charts/kubedb-catalog/templates/redis/redis-4.0.6.yaml, charts/kubedb-catalog/templates/redis/redis-5.0.3.yaml, charts/kubedb-catalog/templates/redis/redis-6.0.6.yaml, charts/kubedb-catalog/templates/redis/redis-6.2.5.yaml
=> Updated Redis-Init version from 0.2.0 to 0.3.0

charts/kubedb-crds/crds/schema.kubedb.com_postgresdatabases.yaml, crds/kubedb-crds.yaml
=> Add PostgresDatabases CRD fixes

catalog/active_versions.json, catalog/backup_tasks.json, catalog/raw/elasticsearch/elasticsearch-5.6.16-kubedb.yaml, catalog/restore_tasks.json, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-5.6.16-kubedb.yaml
=> Add support for Elasticsearch:5.6.16

charts/kubedb-webhook-server/templates/autoscaler/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/dashboard/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/dashboard/validating-webhook.yaml, charts/kubedb-webhook-server/templates/ops-manager/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/ops-manager/validating-webhook.yaml, charts/kubedb-webhook-server/templates/provisioner/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/provisioner/validating-webhook.yaml, charts/kubedb-webhook-server/templates/schema-manager/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/schema-manager/validating-webhook.yaml
=> Simplify webhook-server chart

charts/kubedb/templates/_helpers.tpl
=> Define server.registry in kubedb chart

charts/kubedb-autoscaler/README.md, charts/kubedb-catalog/README.md, charts/kubedb-crds/README.md, charts/kubedb-dashboard/README.md, charts/kubedb-grafana-dashboards/README.md, charts/kubedb-metrics/README.md, charts/kubedb-ops-manager/README.md, charts/kubedb-opscenter/README.md, charts/kubedb-provisioner/README.md, charts/kubedb-schema-manager/README.md, charts/kubedb-ui-server/README.md, charts/kubedb-webhook-server/README.md, charts/kubedb/README.md, hack/fmt/main.go
=> Update chart readmes

charts/kubedb-catalog/README.md, charts/kubedb-catalog/doc.yaml, charts/kubedb-ops-manager/README.md, charts/kubedb-ops-manager/doc.yaml, charts/kubedb-provisioner/README.md, charts/kubedb-provisioner/doc.yaml, charts/kubedb-webhook-server/README.md, charts/kubedb-webhook-server/doc.yaml
=> Make k8s 1.16+ minimum required

charts/kubedb-webhook-server/templates/cluster-role.yaml
=> Add permission to set ca bundle for webhook config

charts/kubedb-opscenter/README.md, charts/kubedb-opscenter/doc.yaml
=> Deploy kubedb-opscenter chart in kubedb namespace

charts/kubedb-grafana-dashboards/dashboards/elasticsearch/elasticsearch_database_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/elasticsearch/elasticsearch_pod_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/elasticsearch/elasticsearch_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-database.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-pod.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-summary.json, charts/kubedb-grafana-dashboards/dashboards/mongodb/mongodb-database-replset-dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mongodb/mongodb-pod-dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mongodb/mongodb-summary-dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mysql/mysql_database_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mysql/mysql_group_replication.json, charts/kubedb-grafana-dashboards/dashboards/mysql/mysql_pod_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mysql/mysql_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_databases_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_pods_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/redis/redis_pod_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/redis/redis_shards_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/redis/redis_summary_dashboard.json
=> Use db as variable for db name

charts/kubedb-grafana-dashboards/dashboards/elasticsearch/elasticsearch_database_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/elasticsearch/elasticsearch_pod_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/elasticsearch/elasticsearch_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-database.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-galera.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-pod.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-summary.json, charts/kubedb-grafana-dashboards/dashboards/mongodb/mongodb-database-replset-dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mongodb/mongodb-pod-dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mongodb/mongodb-summary-dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mysql/mysql_database_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mysql/mysql_group_replication.json, charts/kubedb-grafana-dashboards/dashboards/mysql/mysql_pod_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mysql/mysql_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_databases_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_pods_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/redis/redis_pod_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/redis/redis_shards_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/redis/redis_summary_dashboard.json
ref: https://github.com/appscode/grafana-dashboards/pull/19
=> Make dashboards compatible for Grafana version 7.3.5 to 8.x

charts/kubedb-ui-server/templates/servicemonitor.yaml, charts/kubedb/templates/_helpers.tpl
=> Update service monitor label template for ui-server

catalog/raw/redis/deprecated-redis-4.0.yaml, catalog/raw/redis/deprecated-redis-4.yaml, catalog/raw/redis/deprecated-redis-5.0.yaml, catalog/raw/redis/redis-4.0.11.yaml, catalog/raw/redis/redis-4.0.6.yaml, catalog/raw/redis/redis-5.0.3.yaml, catalog/raw/redis/redis-6.0.6.yaml, catalog/raw/redis/redis-6.2.5.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-4.0.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-4.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-5.0.yaml, charts/kubedb-catalog/templates/redis/redis-4.0.11.yaml, charts/kubedb-catalog/templates/redis/redis-4.0.6.yaml, charts/kubedb-catalog/templates/redis/redis-5.0.3.yaml, charts/kubedb-catalog/templates/redis/redis-6.0.6.yaml, charts/kubedb-catalog/templates/redis/redis-6.2.5.yaml
Signed-off-by: Shaad7 <abdullah.alshaad@appscode.com>
=> Redis init container version update

go.mod, go.sum, vendor/modules.txt
=> Update dependencies(nats client, mongo-driver)

catalog/active_versions.json, catalog/backup_tasks.json, catalog/raw/elasticsearch/elasticsearch-1.3.2-opensearch.yaml, catalog/raw/elasticsearch/elasticsearch-7.17.3-elasticstack.yaml, catalog/raw/elasticsearch/elasticsearch-8.2.0-elasticstack.yaml, catalog/raw/elasticsearch/elasticsearch-8.2.0-kubedb.yaml, catalog/restore_tasks.json, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-1.3.2-opensearch.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-7.17.3-elasticstack.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-8.2.0-elasticstack.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-8.2.0-kubedb.yaml
Signed-off-by: raihankhan <raihan@appscode.com>
=> Add support for ES & Kibana V8

catalog/raw/proxysql/proxysql-2.3.2.yaml, charts/kubedb-catalog/templates/proxysql/proxysql-2.3.2.yaml
=> Add debian tag to proxysqlversion

charts/kubedb-grafana-dashboards/dashboards/elasticsearch/elasticsearch_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-summary.json, charts/kubedb-grafana-dashboards/dashboards/mongodb/mongodb-summary-dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mysql/mysql_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/redis/redis_summary_dashboard.json
=> Fix regex matching for pods

charts/kubedb/Chart.lock, charts/kubedb/Chart.yaml
=> Remove kubedb-metrics from kubedb chart

charts/kubedb-metrics/templates/mongodb/kubedb-com-mongodb.yaml
=> Add mongodb `replicas` metrics configuration

hack/kubernetes/kind.yaml
=> Test against Kubernetes 1.24.0

catalog/raw/proxysql/proxysql-2.3.2-centos.yaml, catalog/raw/proxysql/proxysql-2.3.2-debian.yaml, charts/kubedb-catalog/templates/proxysql/proxysql-2.3.2-centos.yaml, charts/kubedb-catalog/templates/proxysql/proxysql-2.3.2-debian.yaml
=> Update ProxySQL catalog with declarative configuration support 

catalog/raw/mariadb/mariadb-10.4.17.yaml, catalog/raw/mariadb/mariadb-10.5.8.yaml, catalog/raw/mariadb/mariadb-10.6.4.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.4.17.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.5.8.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.6.4.yaml, charts/kubedb-crds/crds/kubedb.com_mariadbs.yaml
=> Update MariaDB Coordinator image tag 

catalog/raw/mysql/mysql-5.7.35-official.yaml, catalog/raw/mysql/mysql-5.7.36-official.yaml, catalog/raw/mysql/mysql-8.0.17-official.yaml, catalog/raw/mysql/mysql-8.0.27-mysql.yaml, catalog/raw/mysql/mysql-8.0.27-official.yaml, catalog/raw/mysql/mysql-8.0.29-official.yaml, catalog/raw/mysql/mysql-8.0.3-official.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.35-official.yaml, charts/kubedb-catalog/templates/mysql/mysql-5.7.36-official.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.17-official.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.27-mysql.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.27-official.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.29-official.yaml, charts/kubedb-catalog/templates/mysql/mysql-8.0.3-official.yaml
Signed-off-by: Mehedi Hasan <mehedi.hasan@appscode.com>
=> Update MySQL coordinator image

charts/kubedb-autoscaler/templates/license-checker-cluster-role.yaml, charts/kubedb-dashboard/templates/license-checker-cluster-role.yaml, charts/kubedb-ops-manager/templates/license-checker-cluster-role.yaml, charts/kubedb-provisioner/templates/license-checker-cluster-role.yaml, charts/kubedb-webhook-server/templates/license-checker-cluster-role.yaml
=> Add permission for license-proxyserver

charts/kubedb-ops-manager/crds/supervisor.appscode.com_recommendations.yaml, hack/scripts/import-crds.sh
=> Add Recommendation crd to ops-manager chart

charts/kubedb-ops-manager/Chart.yaml, charts/kubedb-provisioner/Chart.yaml, charts/kubedb-webhook-server/Chart.yaml
xref: https://github.com/kubedb/elasticsearch/pull/599
=> Fix ES db client issue

charts/kubedb-ops-manager/Chart.yaml, charts/kubedb-provisioner/Chart.yaml, charts/kubedb-webhook-server/Chart.yaml
- Add Security Context Defaulting on PerconaXtraDB
- Fix upgrade details for upgrade version recommendation
=> Release fixes

charts/kubedb-webhook-server/templates/autoscaler/mutating-webhook.yaml
…kconfiguration
Signed-off-by: Arnob kumar saha <arnob@appscode.com>
=> Add all db-types in autoscaler mutatingwebhookConfiguration

.github/workflows/ci.yml, Makefile, charts/kubedb-autoscaler/values.openapiv3_schema.yaml, charts/kubedb-dashboard/values.openapiv3_schema.yaml, charts/kubedb-ops-manager/values.openapiv3_schema.yaml, charts/kubedb-provisioner/values.openapiv3_schema.yaml, charts/kubedb-schema-manager/values.openapiv3_schema.yaml, charts/kubedb-ui-server/values.openapiv3_schema.yaml, charts/kubedb-webhook-server/values.openapiv3_schema.yaml, charts/kubedb/values.openapiv3_schema.yaml, hack/fmt/main.go
=> Use Go 1.19

charts/kubedb-catalog/templates/elasticsearch/elasticsearch-psp.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-psp.yaml, charts/kubedb-catalog/templates/memcached/memcached-psp.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-psp.yaml, charts/kubedb-catalog/templates/mysql/mysql-psp.yaml, charts/kubedb-catalog/templates/perconaxtradb/perconaxtradb-psp.yaml, charts/kubedb-catalog/templates/postgres/postgres-psp.yaml, charts/kubedb-catalog/templates/proxysql/proxysql-psp.yaml, charts/kubedb-catalog/templates/redis/redis-psp.yaml, hack/fmt/main.go, hack/fmt/templates/psp.yaml
=> Don't create PSP object in k8s >= 1.25

.github/workflows/ci.yml, charts/kubedb-ops-manager/templates/operator-psp.yaml, charts/kubedb-provisioner/templates/operator-psp.yaml
=> Test against k8s 1.25.0

charts/kubedb-ops-manager/templates/cluster-role.yaml, charts/kubedb-webhook-server/templates/apiregistration.yaml, charts/kubedb-webhook-server/templates/cluster-role.yaml, charts/kubedb-webhook-server/templates/ops-manager/validating-webhook.yaml
Signed-off-by: Rakibul-Hossain <rakibul.hossain@appscode.com>
=> Add Postgres Logical Replication rbac and validators

.github/workflows/ci.yml, charts/kubedb-metrics/templates/perconaxtradb/catalog-kubedb-com-perconaxtradbversion.yaml, charts/kubedb-metrics/templates/perconaxtradb/kubedb-com-perconaxtradb.yaml, charts/kubedb-metrics/templates/perconaxtradb/ops-kubedb-com-perconaxtradbopsrequest.yaml
=> Add PerconaXtraDB Metrics

catalog/active_versions.json, catalog/raw/proxysql/proxysql-2.4.4-centos.yaml, catalog/raw/proxysql/proxysql-2.4.4-debian.yaml, charts/kubedb-catalog/templates/proxysql/proxysql-2.4.4-centos.yaml, charts/kubedb-catalog/templates/proxysql/proxysql-2.4.4-debian.yaml
=> Add proxysql new version 2.4.4

charts/kubedb-webhook-server/templates/ops-manager/validating-webhook.yaml
Signed-off-by: Rakibul-Hossain <rakibul.hossain@appscode.com>
=> Add Subscriber apiservice

charts/kubedb-metrics/templates/elasticsearch/kubedb-com-elasticsearch.yaml, charts/kubedb-metrics/templates/elasticsearch/ops-kubedb-com-elasticsearchopsrequest.yaml, charts/kubedb-metrics/templates/mariadb/kubedb-com-mariadb.yaml, charts/kubedb-metrics/templates/mariadb/ops-kubedb-com-mariadbopsrequest.yaml, charts/kubedb-metrics/templates/mongodb/kubedb-com-mongodb.yaml, charts/kubedb-metrics/templates/mongodb/ops-kubedb-com-mongodbopsrequest.yaml, charts/kubedb-metrics/templates/mysql/kubedb-com-mysql.yaml, charts/kubedb-metrics/templates/mysql/ops-kubedb-com-mysqlopsrequest.yaml, charts/kubedb-metrics/templates/perconaxtradb/kubedb-com-perconaxtradb.yaml, charts/kubedb-metrics/templates/perconaxtradb/ops-kubedb-com-perconaxtradbopsrequest.yaml, charts/kubedb-metrics/templates/postgres/kubedb-com-postgres.yaml, charts/kubedb-metrics/templates/postgres/ops-kubedb-com-postgresopsrequest.yaml, charts/kubedb-metrics/templates/redis/kubedb-com-redis.yaml, charts/kubedb-metrics/templates/redis/ops-kubedb-com-redisopsrequest.yaml
=> Fix valuePath for app_namespace key

charts/kubedb-webhook-server/templates/autoscaler/mutating-webhook.yaml
Signed-off-by: Arnob kumar saha <arnob@appscode.com>
=> Add mutating webhook for postgresAutoscaler

catalog/raw/elasticsearch/deprecated-elasticsearch-6.3-searchguard.yaml, catalog/raw/elasticsearch/deprecated-elasticsearch-6.3.0-searchguard.yaml, catalog/raw/mongodb/deprecated-mongodb-3.4-official.yaml, catalog/raw/mongodb/deprecated-mongodb-3.6-official.yaml, catalog/raw/mongodb/mongodb-4.0.5-official.yaml, catalog/raw/mongodb/mongodb-4.1.7-official.yaml, catalog/raw/mysql/deprecated-mysql-5.7.29-official.yaml, charts/kubedb-catalog/templates/elasticsearch/deprecated-elasticsearch-6.3-searchguard.yaml, charts/kubedb-catalog/templates/elasticsearch/deprecated-elasticsearch-6.3.0-searchguard.yaml, charts/kubedb-catalog/templates/mongodb/deprecated-mongodb-3.4-official.yaml, charts/kubedb-catalog/templates/mongodb/deprecated-mongodb-3.6-official.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.0.5-official.yaml, charts/kubedb-catalog/templates/mongodb/mongodb-4.1.7-official.yaml, charts/kubedb-catalog/templates/mysql/deprecated-mysql-5.7.29-official.yaml
=> Fix missing docker images

catalog/raw/perconaxtradb/perconaxtradb-8.0.26.yaml, catalog/raw/perconaxtradb/perconaxtradb-8.0.28.yaml, charts/kubedb-catalog/templates/perconaxtradb/perconaxtradb-8.0.26.yaml, charts/kubedb-catalog/templates/perconaxtradb/perconaxtradb-8.0.28.yaml
=> Update Percona XtraDB init container image

catalog/raw/redis/deprecated-redis-4.0.yaml, catalog/raw/redis/deprecated-redis-4.yaml, catalog/raw/redis/deprecated-redis-5.0.yaml, catalog/raw/redis/redis-4.0.11.yaml, catalog/raw/redis/redis-4.0.6.yaml, catalog/raw/redis/redis-5.0.14.yaml, catalog/raw/redis/redis-5.0.3.yaml, catalog/raw/redis/redis-6.0.6.yaml, catalog/raw/redis/redis-6.2.5.yaml, catalog/raw/redis/redis-6.2.7.yaml, catalog/raw/redis/redis-7.0.4.yaml, catalog/raw/redis/redis-7.0.5.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-4.0.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-4.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-5.0.yaml, charts/kubedb-catalog/templates/redis/redis-4.0.11.yaml, charts/kubedb-catalog/templates/redis/redis-4.0.6.yaml, charts/kubedb-catalog/templates/redis/redis-5.0.14.yaml, charts/kubedb-catalog/templates/redis/redis-5.0.3.yaml, charts/kubedb-catalog/templates/redis/redis-6.0.6.yaml, charts/kubedb-catalog/templates/redis/redis-6.2.5.yaml, charts/kubedb-catalog/templates/redis/redis-6.2.7.yaml, charts/kubedb-catalog/templates/redis/redis-7.0.4.yaml, charts/kubedb-catalog/templates/redis/redis-7.0.5.yaml
Signed-off-by: Shaad7 <abdullah.alshaad@appscode.com>
=> Update Redis Init Container Image

catalog/raw/proxysql/proxysql-2.3.2-centos.yaml, catalog/raw/proxysql/proxysql-2.3.2-debian.yaml, charts/kubedb-catalog/templates/proxysql/proxysql-2.3.2-centos.yaml, charts/kubedb-catalog/templates/proxysql/proxysql-2.3.2-debian.yaml
=> Add ProxySQL-2.3.2-debian/centos-v2

charts/kubedb-metrics/templates/proxysql/kubedb-com-proxysql.yaml
=> Fix backend name for ProxySQL

charts/kubedb-catalog/crds/catalog.kubedb.com_proxysqlversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_proxysqlversions.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@daeafa99

charts/kubedb-ops-manager/Chart.yaml, charts/kubedb-provisioner/Chart.yaml
=> Publish fixes

charts/kubedb-ops-manager/Chart.yaml, charts/kubedb-provisioner/Chart.yaml
=> Publish fix for old postgres auth secret labels

charts/kubedb-crds/crds/autoscaling.kubedb.com_proxysqlautoscalers.yaml, charts/kubedb-crds/crds/ops.kubedb.com_proxysqlopsrequests.yaml
=> Update crds for kubedb/apimachinery@f570aabe

charts/kubedb-crds/crds/autoscaling.kubedb.com_proxysqlautoscalers.yaml
=> Update crds for kubedb/apimachinery@89a71807

charts/kubedb-grafana-dashboards/dashboards/elasticsearch/elasticsearch_database_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/elasticsearch/elasticsearch_pod_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/elasticsearch/elasticsearch_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-database.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-pod.json, charts/kubedb-grafana-dashboards/dashboards/mariadb/mariadb-summary.json, charts/kubedb-grafana-dashboards/dashboards/mongodb/mongodb-database-replset-dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mongodb/mongodb-pod-dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mongodb/mongodb-summary-dashboard.json, charts/kubedb-grafana-dashboards/dashboards/mysql/mysql_database_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/perconaxtradb/perconaxtradb-database.json, charts/kubedb-grafana-dashboards/dashboards/perconaxtradb/perconaxtradb-galera.json, charts/kubedb-grafana-dashboards/dashboards/perconaxtradb/perconaxtradb-pod.json, charts/kubedb-grafana-dashboards/dashboards/perconaxtradb/perconaxtradb-summary.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_databases_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_pods_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_summary_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/proxysql/proxysql-database.json, charts/kubedb-grafana-dashboards/dashboards/proxysql/proxysql-pod.json, charts/kubedb-grafana-dashboards/dashboards/proxysql/proxysql-summary.json, charts/kubedb-grafana-dashboards/dashboards/redis/redis_summary_dashboard.json
=> Update Grafana dashboards

.github/workflows/ci.yml, charts/kubedb-grafana-dashboards/README.md, charts/kubedb-grafana-dashboards/data/resources.yaml, charts/kubedb-grafana-dashboards/values.yaml
Signed-off-by: M. A. Muhaimin Sakib <sakib@appscode.com>
=> Add proxysql to kubedb grafana dashboard values and resources

.github/workflows/release-tracker.yml, .github/workflows/release.yml
=> Run GH actions on ubuntu-20.04

charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-ui-server/crds/kubedb.com_postgreses.yaml
=> Update crds for kubedb/apimachinery@b9528283

charts/kubedb-catalog/crds/catalog.kubedb.com_kafkaversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_kafkaversions.yaml, charts/kubedb-crds/crds/kubedb.com_kafkas.yaml, charts/kubedb-ui-server/crds/kubedb.com_kafkas.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@69bc9dec

charts/kubedb-catalog/crds/catalog.kubedb.com_kafkaversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_kafkaversions.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@2a1d4b0b

catalog/raw/redis/deprecated-redis-4.0.yaml, catalog/raw/redis/deprecated-redis-4.yaml, catalog/raw/redis/deprecated-redis-5.0.yaml, catalog/raw/redis/redis-4.0.11.yaml, catalog/raw/redis/redis-4.0.6.yaml, catalog/raw/redis/redis-5.0.14.yaml, catalog/raw/redis/redis-5.0.3.yaml, catalog/raw/redis/redis-6.0.6.yaml, catalog/raw/redis/redis-6.2.5.yaml, catalog/raw/redis/redis-6.2.7.yaml, catalog/raw/redis/redis-7.0.4.yaml, catalog/raw/redis/redis-7.0.5.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-4.0.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-4.yaml, charts/kubedb-catalog/templates/redis/deprecated-redis-5.0.yaml, charts/kubedb-catalog/templates/redis/redis-4.0.11.yaml, charts/kubedb-catalog/templates/redis/redis-4.0.6.yaml, charts/kubedb-catalog/templates/redis/redis-5.0.14.yaml, charts/kubedb-catalog/templates/redis/redis-5.0.3.yaml, charts/kubedb-catalog/templates/redis/redis-6.0.6.yaml, charts/kubedb-catalog/templates/redis/redis-6.2.5.yaml, charts/kubedb-catalog/templates/redis/redis-6.2.7.yaml, charts/kubedb-catalog/templates/redis/redis-7.0.4.yaml, charts/kubedb-catalog/templates/redis/redis-7.0.5.yaml
Signed-off-by: Mehedi Hasan <mehedi.hasan@appscode.com>
=> Update redis-init image

catalog/active_versions.json, catalog/backup_tasks.json, catalog/raw/elasticsearch/elasticsearch-8.5.2-elasticstack.yaml, catalog/restore_tasks.json, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-8.5.2-elasticstack.yaml
Signed-off-by: raihankhan <raihan@appscode.com>
=> Add support for elasticsearch 8.5.2

charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-ui-server/crds/kubedb.com_postgreses.yaml
=> Update crds for kubedb/apimachinery@424a2960

charts/kubedb-provisioner/templates/cluster-role.yaml
Signed-off-by: Rakibul-Hossain <rakibul.hossain@appscode.com>
=> Add `pod/eviction` rbac for provisioner

charts/kubedb-autoscaler/ci/ci-values.yaml, charts/kubedb-ops-manager/ci/ci-values.yaml, charts/kubedb-ops-manager/templates/_helpers.tpl, charts/kubedb-ops-manager/templates/deployment.yaml, charts/kubedb-provisioner/templates/_helpers.tpl, charts/kubedb-provisioner/templates/deployment.yaml, charts/kubedb/templates/_helpers.tpl
=> Read image pull secret from operator flags

catalog/raw/elasticsearch/elasticsearch-1.1.0-opensearch.yaml, catalog/raw/elasticsearch/elasticsearch-1.2.2-opensearch.yaml, catalog/raw/elasticsearch/elasticsearch-1.3.2-opensearch.yaml, catalog/raw/elasticsearch/elasticsearch-7.12.0-elasticstack.yaml, catalog/raw/elasticsearch/elasticsearch-7.13.2-elasticstack.yaml, catalog/raw/elasticsearch/elasticsearch-7.14.0-elasticstack.yaml, catalog/raw/elasticsearch/elasticsearch-7.16.2-elasticstack.yaml, catalog/raw/elasticsearch/elasticsearch-7.17.3-elasticstack.yaml, catalog/raw/elasticsearch/elasticsearch-7.9.1-elasticstack.yaml, catalog/raw/elasticsearch/elasticsearch-8.2.0-elasticstack.yaml, catalog/raw/elasticsearch/elasticsearch-8.5.2-elasticstack.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-1.1.0-opensearch.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-1.2.2-opensearch.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-1.3.2-opensearch.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-7.12.0-elasticstack.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-7.13.2-elasticstack.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-7.14.0-elasticstack.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-7.16.2-elasticstack.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-7.17.3-elasticstack.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-7.9.1-elasticstack.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-8.2.0-elasticstack.yaml, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-8.5.2-elasticstack.yaml
- Update images for changing dashboard user from root to non-root
Signed-off-by: raihankhan <raihan@appscode.com>
=> Update Dashboard init container images

charts/kubedb-provisioner/templates/cluster-role.yaml
=> Add Sidekick on Cluster Role (POC)

catalog/raw/pgbouncer/pgbouncer-1.17.0.yaml, catalog/raw/pgbouncer/pgbouncer-1.18.0.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_pgbouncerversions.yaml, charts/kubedb-catalog/templates/pgbouncer/pgbouncer-1.17.0.yaml, charts/kubedb-catalog/templates/pgbouncer/pgbouncer-1.18.0.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_pgbouncerversions.yaml, charts/kubedb-webhook-server/templates/cluster-role.yaml, crds/kubedb-catalog-crds.yaml
=> Add `SecurityContext` & remove `initContainer` from `pgbouncerVersion.spec`

charts/kubedb-ops-manager/Chart.yaml
=> Use ops-manager@v0.19.1

charts/kubedb-provisioner/Chart.yaml
=> Add acme support for pgbouncer exporter

charts/kubedb-crds/crds/ops.kubedb.com_elasticsearchopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_etcdopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mariadbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_memcachedopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mongodbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mysqlopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_perconaxtradbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_pgbounceropsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_postgresopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_proxysqlopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_redisopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_redissentinelopsrequests.yaml
=> Update crds for kubedb/apimachinery@b51ef1ea

charts/kubedb-ops-manager/crds/scanner.appscode.com_imagescanreports.yaml, charts/kubedb-ops-manager/crds/scanner.appscode.com_imagescanrequests.yaml, charts/kubedb-ops-manager/templates/cluster-role.yaml, hack/scripts/import-crds.sh
=> Update ops-manager chart for recommendation cve reports

charts/kubedb-crds/crds/kubedb.com_kafkas.yaml, charts/kubedb-ui-server/crds/kubedb.com_kafkas.yaml
=> Update crds for kubedb/apimachinery@c787eb94

.github/workflows/ci.yml
=> Test against K8s 1.27.0

charts/kubedb-crds/crds/dashboard.kubedb.com_elasticsearchdashboards.yaml, charts/kubedb-crds/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-crds/crds/kubedb.com_etcds.yaml, charts/kubedb-crds/crds/kubedb.com_kafkas.yaml, charts/kubedb-crds/crds/kubedb.com_mariadbs.yaml, charts/kubedb-crds/crds/kubedb.com_memcacheds.yaml, charts/kubedb-crds/crds/kubedb.com_mongodbs.yaml, charts/kubedb-crds/crds/kubedb.com_mysqls.yaml, charts/kubedb-crds/crds/kubedb.com_perconaxtradbs.yaml, charts/kubedb-crds/crds/kubedb.com_pgbouncers.yaml, charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-crds/crds/kubedb.com_proxysqls.yaml, charts/kubedb-crds/crds/kubedb.com_redises.yaml, charts/kubedb-crds/crds/kubedb.com_redissentinels.yaml, charts/kubedb-crds/crds/ops.kubedb.com_redisopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_redissentinelopsrequests.yaml, charts/kubedb-ui-server/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-ui-server/crds/kubedb.com_etcds.yaml, charts/kubedb-ui-server/crds/kubedb.com_kafkas.yaml, charts/kubedb-ui-server/crds/kubedb.com_mariadbs.yaml, charts/kubedb-ui-server/crds/kubedb.com_memcacheds.yaml, charts/kubedb-ui-server/crds/kubedb.com_mongodbs.yaml, charts/kubedb-ui-server/crds/kubedb.com_mysqls.yaml, charts/kubedb-ui-server/crds/kubedb.com_perconaxtradbs.yaml, charts/kubedb-ui-server/crds/kubedb.com_pgbouncers.yaml, charts/kubedb-ui-server/crds/kubedb.com_postgreses.yaml, charts/kubedb-ui-server/crds/kubedb.com_proxysqls.yaml, charts/kubedb-ui-server/crds/kubedb.com_redises.yaml, charts/kubedb-ui-server/crds/kubedb.com_redissentinels.yaml
=> Update crds for kubedb/apimachinery@70ebcf52

charts/kubedb-crds/crds/kubedb.com_proxysqls.yaml, charts/kubedb-ui-server/crds/kubedb.com_proxysqls.yaml
=> Update crds for kubedb/apimachinery@19397df9

charts/kubedb-crds/crds/kubedb.com_kafkas.yaml, charts/kubedb-ui-server/crds/kubedb.com_kafkas.yaml
=> Update crds for kubedb/apimachinery@224dd567

charts/kubedb-catalog/crds/catalog.kubedb.com_kafkaversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_mysqlversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_kafkaversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mysqlversions.yaml, charts/kubedb-crds/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-crds/crds/kubedb.com_etcds.yaml, charts/kubedb-crds/crds/kubedb.com_kafkas.yaml, charts/kubedb-crds/crds/kubedb.com_mariadbs.yaml, charts/kubedb-crds/crds/kubedb.com_mongodbs.yaml, charts/kubedb-crds/crds/kubedb.com_mysqls.yaml, charts/kubedb-crds/crds/kubedb.com_perconaxtradbs.yaml, charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-crds/crds/kubedb.com_redises.yaml, charts/kubedb-ui-server/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-ui-server/crds/kubedb.com_etcds.yaml, charts/kubedb-ui-server/crds/kubedb.com_kafkas.yaml, charts/kubedb-ui-server/crds/kubedb.com_mariadbs.yaml, charts/kubedb-ui-server/crds/kubedb.com_mongodbs.yaml, charts/kubedb-ui-server/crds/kubedb.com_mysqls.yaml, charts/kubedb-ui-server/crds/kubedb.com_perconaxtradbs.yaml, charts/kubedb-ui-server/crds/kubedb.com_postgreses.yaml, charts/kubedb-ui-server/crds/kubedb.com_redises.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@8e2aab0c

charts/kubedb-crds/crds/ops.kubedb.com_kafkaopsrequests.yaml, charts/kubedb-ops-manager/templates/cluster-role.yaml, charts/kubedb-webhook-server/templates/ops-manager/validating-webhook.yaml
Signed-off-by: obaydullahmhs <obaydullah@appscode.com>
=> Add kafka ops request crd

charts/kubedb-crds/crds/ops.kubedb.com_elasticsearchopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mariadbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_memcachedopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mongodbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mysqlopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_perconaxtradbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_postgresopsrequests.yaml
=> Update crds for kubedb/apimachinery@f684560c

charts/kubedb-crds/crds/ops.kubedb.com_elasticsearchopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mariadbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_memcachedopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mongodbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mysqlopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_perconaxtradbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_postgresopsrequests.yaml
=> Update crds for kubedb/apimachinery@b69c766e

charts/kubedb-catalog/crds/catalog.kubedb.com_elasticsearchversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_etcdversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_mongodbversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_perconaxtradbversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_postgresversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_redisversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_elasticsearchversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_etcdversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mongodbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_perconaxtradbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_postgresversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_redisversions.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@f5de4a28

charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-crds/crds/ops.kubedb.com_postgresopsrequests.yaml, charts/kubedb-ui-server/crds/kubedb.com_postgreses.yaml
=> Update crds for kubedb/apimachinery@96238937

charts/kubedb-crds/crds/autoscaling.kubedb.com_elasticsearchautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mariadbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mongodbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mysqlautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_perconaxtradbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_postgresautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_proxysqlautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_redisautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_redissentinelautoscalers.yaml, charts/kubedb-crds/crds/ops.kubedb.com_elasticsearchopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_kafkaopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mariadbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mongodbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mysqlopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_perconaxtradbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_postgresopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_proxysqlopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_redisopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_redissentinelopsrequests.yaml
=> Update crds for kubedb/apimachinery@bf7aa205

charts/kubedb-crds/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-crds/crds/kubedb.com_kafkas.yaml, charts/kubedb-ui-server/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-ui-server/crds/kubedb.com_kafkas.yaml
=> Update crds for kubedb/apimachinery@1d455662

charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-ui-server/crds/kubedb.com_postgreses.yaml
=> Update crds for kubedb/apimachinery@c99d3ab1

charts/kubedb-crds/crds/autoscaling.kubedb.com_elasticsearchautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mariadbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mongodbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mysqlautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_perconaxtradbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_postgresautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_proxysqlautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_redisautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_redissentinelautoscalers.yaml
=> Update crds for kubedb/apimachinery@750f6385

charts/kubedb-catalog/crds/catalog.kubedb.com_mongodbversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_mysqlversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_postgresversions.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mysqlarchivers.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mongodbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mysqlversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_postgresversions.yaml, charts/kubedb-crds/crds/kubedb.com_mysqls.yaml, charts/kubedb-ui-server/crds/kubedb.com_mysqls.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@61b590f7

charts/kubedb-catalog/crds/catalog.kubedb.com_kafkaconnectorversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_kafkaversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_mongodbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_kafkaconnectorversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_kafkaversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mongodbversions.yaml, charts/kubedb-kubestash-catalog/crds/addons.kubestash.com_addons.yaml, charts/kubedb-kubestash-catalog/crds/addons.kubestash.com_functions.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@a72bb1ff

charts/kubedb-catalog/crds/catalog.kubedb.com_singlestoreversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_singlestoreversions.yaml, charts/kubedb-crds/crds/kubedb.com_singlestores.yaml, charts/kubedb-ui-server/crds/kubedb.com_singlestores.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@e78c6ff7

charts/kubedb-catalog/crds/catalog.kubedb.com_druidversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_kafkaconnectorversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_solrversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_druidversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_kafkaconnectorversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_solrversions.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@0f8ac911

catalog/kubedb/raw/rabbitmq/rabbitmq-3.12.12.yaml, catalog/kubedb/raw/solr/solr-8.11.0.yaml, catalog/kubedb/raw/solr/solr-9.4.0.yaml, charts/kubedb-catalog/templates/solr/solr-8.11.0.yaml, charts/kubedb-catalog/templates/solr/solr-9.4.0.yaml, charts/kubedb-catalog/templates/solr/solr-psp.yaml, charts/kubedb-webhook-server/templates/provisioner/mutating-webhook.yaml, charts/kubedb-webhook-server/templates/provisioner/validating-webhook.yaml
Signed-off-by: pritamdas99 <pritam@appscode.com>
=> Update Solr webhook helm charts.

charts/kubedb-crds/crds/kubedb.com_druids.yaml, charts/kubedb-ui-server/crds/kubedb.com_druids.yaml
=> Update crds for kubedb/apimachinery@f614ab97

catalog/kubedb/raw/postgres/postgres-10.23-official.yaml, catalog/kubedb/raw/postgres/postgres-11.11-timescaledb.yaml, catalog/kubedb/raw/postgres/postgres-11.14-postgis.yaml, catalog/kubedb/raw/postgres/postgres-11.22-official.yaml, catalog/kubedb/raw/postgres/postgres-12.17-official.yaml, catalog/kubedb/raw/postgres/postgres-12.6-timescaledb.yaml, catalog/kubedb/raw/postgres/postgres-12.9-postgis.yaml, catalog/kubedb/raw/postgres/postgres-13.13-official.yaml, catalog/kubedb/raw/postgres/postgres-13.2-timescaledb.yaml, catalog/kubedb/raw/postgres/postgres-13.5-postgis.yaml, catalog/kubedb/raw/postgres/postgres-14.1-postgis.yaml, catalog/kubedb/raw/postgres/postgres-14.1-timescaledb.yaml, catalog/kubedb/raw/postgres/postgres-14.10-official.yaml, catalog/kubedb/raw/postgres/postgres-15.5-official.yaml, catalog/kubedb/raw/postgres/postgres-16.1-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-10.23-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.11-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.14-postgis.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.22-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.17-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.6-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.9-postgis.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.13-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.2-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.5-postgis.yaml, charts/kubedb-catalog/templates/postgres/postgres-14.1-postgis.yaml, charts/kubedb-catalog/templates/postgres/postgres-14.1-timescaledb.yaml, charts/kubedb-catalog/templates/postgres/postgres-14.10-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-15.5-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-16.1-official.yaml
=> Upgrade postgres exporter image

charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_databases_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_pods_dashboard.json, charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_summary_dashboard.json
=> Postgres grafana alert dashboards

charts/kubedb-crds/crds/kubedb.com_ferretdbs.yaml, charts/kubedb-ui-server/crds/kubedb.com_ferretdbs.yaml
=> Update crds for kubedb/apimachinery@c711b3ab

charts/kubedb-crds/crds/autoscaling.kubedb.com_elasticsearchautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mariadbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mongodbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mysqlautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_perconaxtradbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_postgresautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_redisautoscalers.yaml, charts/kubedb-crds/crds/ops.kubedb.com_elasticsearchopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_kafkaopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mariadbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mongodbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mysqlopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_perconaxtradbopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_postgresopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_redisopsrequests.yaml
=> Update crds for kubedb/apimachinery@89a65996

charts/kubedb-crds/crds/kubedb.com_rabbitmqs.yaml, charts/kubedb-ui-server/crds/kubedb.com_rabbitmqs.yaml
=> Update crds for kubedb/apimachinery@aa33c6e8

charts/kubedb-crds/crds/kubedb.com_zookeepers.yaml, charts/kubedb-ui-server/crds/kubedb.com_zookeepers.yaml
=> Update crds for kubedb/apimachinery@3a9f337b

charts/kubedb-crds/crds/kubedb.com_zookeepers.yaml, charts/kubedb-ui-server/crds/kubedb.com_zookeepers.yaml
=> Update crds for kubedb/apimachinery@64f555c3

charts/kubedb-crds/crds/kubedb.com_zookeepers.yaml, charts/kubedb-ui-server/crds/kubedb.com_zookeepers.yaml
=> Update crds for kubedb/apimachinery@40d63454

charts/kubedb-crds/crds/kafka.kubedb.com_connectors.yaml, charts/kubedb-crds/crds/kubedb.com_druids.yaml, charts/kubedb-crds/crds/kubedb.com_pgpools.yaml, charts/kubedb-crds/crds/kubedb.com_solrs.yaml, charts/kubedb-ui-server/crds/kubedb.com_druids.yaml, charts/kubedb-ui-server/crds/kubedb.com_pgpools.yaml, charts/kubedb-ui-server/crds/kubedb.com_solrs.yaml
=> Update crds for kubedb/apimachinery@5344c20e

charts/kubedb-ops-manager/templates/cluster-role.yaml
=> Add PetSet Resource verbs for SVA

charts/kubedb-crds/crds/kubedb.com_singlestores.yaml, charts/kubedb-ui-server/crds/kubedb.com_singlestores.yaml
=> Update crds for kubedb/apimachinery@9553f55b

charts/kubedb-crds/crds/autoscaling.kubedb.com_kafkaautoscalers.yaml
=> Update crds for kubedb/apimachinery@403b7380

catalog/kubedb/raw/pgpool/pgpool-4.4.5.yaml, catalog/kubedb/raw/pgpool/pgpool-4.5.0.yaml, charts/kubedb-catalog/templates/pgpool/pgpool-4.4.5.yaml, charts/kubedb-catalog/templates/pgpool/pgpool-4.5.0.yaml, charts/kubedb-grafana-dashboards/dashboards/pgpool/pgpool-database.json, charts/kubedb-grafana-dashboards/dashboards/pgpool/pgpool-pod.json, charts/kubedb-grafana-dashboards/dashboards/pgpool/pgpool-summary.json, charts/kubedb-grafana-dashboards/data/resources.yaml, charts/kubedb-metrics/templates/pgpool/catalog-kubedb-com-pgpoolversion.yaml, charts/kubedb-metrics/templates/pgpool/kubedb-com-pgpool.yaml
Signed-off-by: MobarakHsn <mobarak@appscode.com>
=> Add Pgpool MetricsConfiguration, Grafana Dashboards & Exporter to Catalog

charts/kubedb-crds/crds/kubedb.com_druids.yaml, charts/kubedb-crds/crds/kubedb.com_ferretdbs.yaml, charts/kubedb-crds/crds/kubedb.com_pgpools.yaml, charts/kubedb-crds/crds/kubedb.com_rabbitmqs.yaml, charts/kubedb-crds/crds/kubedb.com_singlestores.yaml, charts/kubedb-crds/crds/kubedb.com_solrs.yaml, charts/kubedb-crds/crds/kubedb.com_zookeepers.yaml, charts/kubedb-ui-server/crds/kubedb.com_druids.yaml, charts/kubedb-ui-server/crds/kubedb.com_ferretdbs.yaml, charts/kubedb-ui-server/crds/kubedb.com_pgpools.yaml, charts/kubedb-ui-server/crds/kubedb.com_rabbitmqs.yaml, charts/kubedb-ui-server/crds/kubedb.com_singlestores.yaml, charts/kubedb-ui-server/crds/kubedb.com_solrs.yaml, charts/kubedb-ui-server/crds/kubedb.com_zookeepers.yaml
=> Update crds for kubedb/apimachinery@3d020832

charts/kubedb-crds/crds/kubedb.com_druids.yaml, charts/kubedb-ui-server/crds/kubedb.com_druids.yaml
=> Update crds for kubedb/apimachinery@362c68b4

charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-ui-server/crds/kubedb.com_postgreses.yaml
=> Update crds for kubedb/apimachinery@4a4c3980

charts/kubedb-crds/crds/kubedb.com_solrs.yaml, charts/kubedb-ui-server/crds/kubedb.com_solrs.yaml
=> Update crds for kubedb/apimachinery@ed0e97c8

.github/workflows/ci.yml, .github/workflows/cve-report.yml, go.sum
=> Use Go 1.22

charts/kubedb-kubestash-catalog/crds/addons.kubestash.com_addons.yaml
=> Update crds for kubedb/apimachinery@eca0297e

charts/kubedb-catalog/crds/catalog.kubedb.com_mssqlversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mssqlversions.yaml, charts/kubedb-crds/crds/kubedb.com_mssqls.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mssqlopsrequests.yaml, charts/kubedb-ui-server/crds/kubedb.com_mssqls.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@6efef42b

charts/kubedb-crds/crds/kubedb.com_pgpools.yaml, charts/kubedb-ui-server/crds/kubedb.com_pgpools.yaml
=> Update crds for kubedb/apimachinery@7fb3d561

charts/kubedb-crds/crds/autoscaling.kubedb.com_elasticsearchautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_kafkaautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mariadbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mongodbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mysqlautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_perconaxtradbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_postgresautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_rabbitmqautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_redisautoscalers.yaml, charts/kubedb-kubestash-catalog/crds/addons.kubestash.com_functions.yaml
=> Update crds for kubedb/apimachinery@71b8b1a6

charts/kubedb-crds/crds/kubedb.com_zookeepers.yaml, charts/kubedb-ui-server/crds/kubedb.com_zookeepers.yaml
=> Update crds for kubedb/apimachinery@a74eb3db

charts/kubedb-grafana-dashboards/dashboards/solr/solr-summary.json
Signed-off-by: pritamdas99 <pritam@appscode.com>
=> Fix summary dashboard job name.

charts/kubedb-crds/crds/kubedb.com_pgbouncers.yaml, charts/kubedb-ui-server/crds/kubedb.com_pgbouncers.yaml
=> Update crds for kubedb/apimachinery@945f983c

charts/kubedb-crds/crds/kubedb.com_pgbouncers.yaml, charts/kubedb-ui-server/crds/kubedb.com_pgbouncers.yaml
=> Update crds for kubedb/apimachinery@0744dd0c

catalog/kubedb/raw/mssqlserver/mssqlserver-2022.yaml, charts/kubedb-catalog/templates/mssqlserver/mssqlserver-2022.yaml, charts/kubedb-provisioner/templates/cluster-role.yaml
Signed-off-by: Neaj Morshad <neaj@appscode.com>
=> Add MSSQL Server Rbac and Use updated image for TLS

charts/kubedb-kubestash-catalog/crds/addons.kubestash.com_addons.yaml, charts/kubedb-kubestash-catalog/crds/addons.kubestash.com_functions.yaml
=> Update crds for kubedb/apimachinery@acca053a

charts/kubedb-crds/crds/kubedb.com_kafkas.yaml, charts/kubedb-crds/crds/kubedb.com_rabbitmqs.yaml, charts/kubedb-ui-server/crds/kubedb.com_kafkas.yaml, charts/kubedb-ui-server/crds/kubedb.com_rabbitmqs.yaml
=> Update crds for kubedb/apimachinery@c1a2e274

catalog/kubedb/active_versions.json, catalog/kubedb/backup_tasks.json, catalog/kubedb/raw/elasticsearch/elasticsearch-8.14.1-elasticstack.yaml, catalog/kubedb/restore_tasks.json, charts/kubedb-catalog/templates/elasticsearch/elasticsearch-8.14.1-elasticstack.yaml
Signed-off-by: pritamdas99 [pritam@appscode.com](mailto:pritam@appscode.com)
=> Add support for elasticsearch 8.14.1

charts/kubedb-crds/crds/ops.kubedb.com_solropsrequests.yaml
=> Update crds for kubedb/apimachinery@9809d94e

charts/kubedb-metrics/templates/elasticsearch/kubedb-com-elasticsearch.yaml, charts/kubedb-metrics/templates/kafka/kubedb-com-kafka.yaml, charts/kubedb-metrics/templates/mariadb/kubedb-com-mariadb.yaml, charts/kubedb-metrics/templates/mongodb/kubedb-com-mongodb.yaml, charts/kubedb-metrics/templates/mysql/kubedb-com-mysql.yaml, charts/kubedb-metrics/templates/perconaxtradb/kubedb-com-perconaxtradb.yaml, charts/kubedb-metrics/templates/postgres/kubedb-com-postgres.yaml, charts/kubedb-metrics/templates/proxysql/kubedb-com-proxysql.yaml, charts/kubedb-metrics/templates/redis/kubedb-com-redis.yaml
=> fix metrics configuration

charts/kubedb-crds/crds/autoscaling.kubedb.com_clickhouseautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_ferretdbautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mssqlserverautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_pgbouncerautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_solrautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_zookeeperautoscalers.yaml
=> Update crds for kubedb/apimachinery@4af05fd8

charts/kubedb-crds/crds/autoscaling.kubedb.com_pgbouncerautoscalers.yaml, charts/kubedb-crds/crds/kafka.kubedb.com_restproxies.yaml, charts/kubedb-crds/crds/ops.kubedb.com_ferretdbopsrequests.yaml
=> Update crds for kubedb/apimachinery@3f96b907

charts/kubedb-catalog/crds/catalog.kubedb.com_mssqlserverversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mssqlserverversions.yaml, charts/kubedb-crds/crds/kubedb.com_mssqlservers.yaml, charts/kubedb-crds/crds/ops.kubedb.com_solropsrequests.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@1d9ee37f

charts/kubedb-catalog/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_mongodbversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_mssqlserverversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_mysqlversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_postgresversions.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mssqlserverarchivers.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mongodbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mssqlserverversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mysqlversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_postgresversions.yaml, charts/kubedb-crds/crds/kubedb.com_mssqlservers.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@0f09eede

catalog/kubedb/raw/mssqlserver/mssqlserver-2022.yaml, catalog/kubestash/raw/postgres/postgres-backup-function.yaml, catalog/kubestash/raw/postgres/postgres-restore-function.yaml, charts/kubedb-catalog/templates/mssqlserver/mssqlserver-2022.yaml, charts/kubedb-kubestash-catalog/templates/postgres/postgres-backup.yaml, charts/kubedb-kubestash-catalog/templates/postgres/postgres-restore.yaml
=> Add postgres multiple db version support for kubestash function

charts/kubedb-crds/crds/kubedb.com_clickhouses.yaml, charts/kubedb-crds/crds/kubedb.com_druids.yaml, charts/kubedb-crds/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-crds/crds/kubedb.com_etcds.yaml, charts/kubedb-crds/crds/kubedb.com_ferretdbs.yaml, charts/kubedb-crds/crds/kubedb.com_kafkas.yaml, charts/kubedb-crds/crds/kubedb.com_mariadbs.yaml, charts/kubedb-crds/crds/kubedb.com_memcacheds.yaml, charts/kubedb-crds/crds/kubedb.com_mongodbs.yaml, charts/kubedb-crds/crds/kubedb.com_mssqlservers.yaml, charts/kubedb-crds/crds/kubedb.com_mysqls.yaml, charts/kubedb-crds/crds/kubedb.com_perconaxtradbs.yaml, charts/kubedb-crds/crds/kubedb.com_pgbouncers.yaml, charts/kubedb-crds/crds/kubedb.com_pgpools.yaml, charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-crds/crds/kubedb.com_proxysqls.yaml, charts/kubedb-crds/crds/kubedb.com_rabbitmqs.yaml, charts/kubedb-crds/crds/kubedb.com_redises.yaml, charts/kubedb-crds/crds/kubedb.com_redissentinels.yaml, charts/kubedb-crds/crds/kubedb.com_singlestores.yaml, charts/kubedb-crds/crds/kubedb.com_solrs.yaml, charts/kubedb-crds/crds/kubedb.com_zookeepers.yaml, charts/kubedb-crds/crds/ops.kubedb.com_singlestoreopsrequests.yaml
=> Update crds for kubedb/apimachinery@4b2e4872

.github/workflows/ci.yml, .github/workflows/cve-report.yml, .github/workflows/publish-oci.yml, .github/workflows/release-tracker.yml, .github/workflows/release.yml, Makefile
=> Use Go 1.23

catalog/kubedb/raw/mssqlserver/mssqlserver-2022.yaml, charts/kubedb-catalog/templates/mssqlserver/mssqlserver-2022.yaml, charts/kubedb-metrics/templates/mssqlserver/catalog-kubedb-com-mssqlserverversion.yaml, charts/kubedb-metrics/templates/mssqlserver/kubedb-com-mssqlserver.yaml
=> Add Microsoft SQL Server MetricsConfiguration

catalog/kubedb/raw/redis/redis-4.0.11.yaml, catalog/kubedb/raw/redis/redis-5.0.14.yaml, catalog/kubedb/raw/redis/redis-6.0.20.yaml, catalog/kubedb/raw/redis/redis-6.2.14.yaml, catalog/kubedb/raw/redis/redis-7.0.14.yaml, catalog/kubedb/raw/redis/redis-7.0.15.yaml, catalog/kubedb/raw/redis/redis-7.2.3.yaml, catalog/kubedb/raw/redis/redis-7.2.4.yaml, charts/kubedb-catalog/templates/redis/redis-4.0.11.yaml, charts/kubedb-catalog/templates/redis/redis-5.0.14.yaml, charts/kubedb-catalog/templates/redis/redis-6.0.20.yaml, charts/kubedb-catalog/templates/redis/redis-6.2.14.yaml, charts/kubedb-catalog/templates/redis/redis-7.0.14.yaml, charts/kubedb-catalog/templates/redis/redis-7.0.15.yaml, charts/kubedb-catalog/templates/redis/redis-7.2.3.yaml, charts/kubedb-catalog/templates/redis/redis-7.2.4.yaml
=> Add updateconstraint for Redis

catalog/kubedb/raw/postgres/postgres-10.23-official.yaml, catalog/kubedb/raw/postgres/postgres-11.22-official.yaml, catalog/kubedb/raw/postgres/postgres-12.17-official.yaml, catalog/kubedb/raw/postgres/postgres-13.13-official.yaml, catalog/kubedb/raw/postgres/postgres-14.10-official.yaml, catalog/kubedb/raw/postgres/postgres-14.13-official.yaml, catalog/kubedb/raw/postgres/postgres-15.5-official.yaml, catalog/kubedb/raw/postgres/postgres-15.6-official.yaml, catalog/kubedb/raw/postgres/postgres-16.1-official.yaml, catalog/kubedb/raw/postgres/postgres-16.2-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-10.23-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-11.22-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-12.17-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-13.13-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-14.10-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-14.13-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-15.5-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-15.6-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-16.1-official.yaml, charts/kubedb-catalog/templates/postgres/postgres-16.2-official.yaml
Signed-off-by: souravbiswassanto <sourav.cse4.bu@gmail.com>
=> Postgres catalog update constraints

catalog/kubedb/raw/mariadb/mariadb-10.10.7.yaml, catalog/kubedb/raw/mariadb/mariadb-10.11.6.yaml, catalog/kubedb/raw/mariadb/mariadb-10.4.32.yaml, catalog/kubedb/raw/mariadb/mariadb-10.5.23.yaml, catalog/kubedb/raw/mariadb/mariadb-10.6.16.yaml, catalog/kubedb/raw/mariadb/mariadb-11.0.4.yaml, catalog/kubedb/raw/mariadb/mariadb-11.1.3.yaml, catalog/kubedb/raw/mariadb/mariadb-11.2.2.yaml, catalog/kubedb/raw/mariadb/mariadb-11.3.2.yaml, catalog/kubedb/raw/mariadb/mariadb-11.4.3.yaml, catalog/kubedb/raw/mariadb/mariadb-11.5.2.yaml, catalog/kubedb/raw/perconaxtradb/perconaxtradb-8.0.26.yaml, catalog/kubedb/raw/perconaxtradb/perconaxtradb-8.0.28.yaml, catalog/kubedb/raw/perconaxtradb/perconaxtradb-8.0.31.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.10.7.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.11.6.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.4.32.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.5.23.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-10.6.16.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-11.0.4.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-11.1.3.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-11.2.2.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-11.3.2.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-11.4.3.yaml, charts/kubedb-catalog/templates/mariadb/mariadb-11.5.2.yaml, charts/kubedb-catalog/templates/perconaxtradb/perconaxtradb-8.0.26.yaml, charts/kubedb-catalog/templates/perconaxtradb/perconaxtradb-8.0.28.yaml, charts/kubedb-catalog/templates/perconaxtradb/perconaxtradb-8.0.31.yaml
Signed-off-by: SK Ali Arman <arman@appscode.com>
=> Add UpdateContraints for MariaDB, PerconaXtraDB Version CR

charts/kubedb-catalog/crds/catalog.kubedb.com_memcachedversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_memcachedversions.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@f4c829bd

charts/kubedb-crds/crds/ops.kubedb.com_pgbounceropsrequests.yaml
=> Update crds for kubedb/apimachinery@9ed3d95a

charts/kubedb-catalog/crds/catalog.kubedb.com_cassandraversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_cassandraversions.yaml, charts/kubedb-crds/crds/kubedb.com_cassandras.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@c4598e14

charts/kubedb-crds/crds/autoscaling.kubedb.com_cassandraautoscalers.yaml
=> Update crds for kubedb/apimachinery@f622d2d3

charts/kubedb-crds/crds/ops.kubedb.com_zookeeperopsrequests.yaml
=> Update crds for kubedb/apimachinery@639cafff

charts/kubedb-crds/crds/kubedb.com_pgbouncers.yaml, charts/kubedb-crds/crds/ops.kubedb.com_pgbounceropsrequests.yaml
=> Update crds for kubedb/apimachinery@38154e49

charts/kubedb-catalog/crds/catalog.kubedb.com_clickhouseversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_pgpoolversions.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mssqlserverautoscalers.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_clickhouseversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_pgpoolversions.yaml, charts/kubedb-crds/crds/elasticsearch.kubedb.com_elasticsearchdashboards.yaml, charts/kubedb-crds/crds/kubedb.com_clickhouses.yaml, charts/kubedb-crds/crds/kubedb.com_mssqlservers.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mssqlserveropsrequests.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@706baeb4

catalog/kubedb/raw/clickhouse/clickhouse-24.4.1.yaml, charts/kubedb-catalog/templates/clickhouse/clickhouse-24.4.1.yaml
Add Support for KubeDB Managed ClickHouse Keeper and internal Clickhouse Keeper
=> Add Support for KubeDB Managed, Internal ClickHouse Keeper

charts/kubedb-crds/crds/kubedb.com_solrs.yaml, charts/kubedb-crds/crds/ops.kubedb.com_solropsrequests.yaml
=> Update crds for kubedb/apimachinery@1a812915

charts/kubedb-catalog/crds/catalog.kubedb.com_solrversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_solrversions.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@f7d0e37e

charts/kubedb-catalog/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_proxysqlversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_proxysqlversions.yaml, charts/kubedb-crds/crds/kubedb.com_redissentinels.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@7f1a71f4

charts/kubedb-crds/crds/kubedb.com_memcacheds.yaml
=> Update crds for kubedb/apimachinery@cb06c3f8

charts/kubedb-crds/crds/kubedb.com_memcacheds.yaml
=> Update crds for kubedb/apimachinery@f9f5d3f7

charts/kubedb-crds/crds/kubedb.com_cassandras.yaml, charts/kubedb-crds/crds/kubedb.com_clickhouses.yaml, charts/kubedb-crds/crds/kubedb.com_druids.yaml, charts/kubedb-crds/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-crds/crds/kubedb.com_etcds.yaml, charts/kubedb-crds/crds/kubedb.com_ferretdbs.yaml, charts/kubedb-crds/crds/kubedb.com_kafkas.yaml, charts/kubedb-crds/crds/kubedb.com_mariadbs.yaml, charts/kubedb-crds/crds/kubedb.com_memcacheds.yaml, charts/kubedb-crds/crds/kubedb.com_mongodbs.yaml, charts/kubedb-crds/crds/kubedb.com_mssqlservers.yaml, charts/kubedb-crds/crds/kubedb.com_mysqls.yaml, charts/kubedb-crds/crds/kubedb.com_perconaxtradbs.yaml, charts/kubedb-crds/crds/kubedb.com_pgbouncers.yaml, charts/kubedb-crds/crds/kubedb.com_pgpools.yaml, charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-crds/crds/kubedb.com_proxysqls.yaml, charts/kubedb-crds/crds/kubedb.com_rabbitmqs.yaml, charts/kubedb-crds/crds/kubedb.com_redises.yaml, charts/kubedb-crds/crds/kubedb.com_redissentinels.yaml, charts/kubedb-crds/crds/kubedb.com_singlestores.yaml, charts/kubedb-crds/crds/kubedb.com_solrs.yaml, charts/kubedb-crds/crds/kubedb.com_zookeepers.yaml
=> Update crds for kubedb/apimachinery@5eb3c722

charts/kubedb-crds/crds/kubedb.com_zookeepers.yaml, charts/kubedb-crds/crds/ops.kubedb.com_zookeeperopsrequests.yaml
=> Update crds for kubedb/apimachinery@765bca2a

charts/kubedb-crds/crds/kubedb.com_druids.yaml, charts/kubedb-crds/crds/ops.kubedb.com_druidopsrequests.yaml
=> Update crds for kubedb/apimachinery@405c179f

charts/kubedb-crds/crds/ops.kubedb.com_singlestoreopsrequests.yaml
=> Update crds for kubedb/apimachinery@c57cfcac

charts/kubedb-crds/crds/ops.kubedb.com_pgbounceropsrequests.yaml, charts/kubedb-crds/crds/postgres.kubedb.com_publishers.yaml, charts/kubedb-crds/crds/postgres.kubedb.com_subscribers.yaml
=> Update crds for kubedb/apimachinery@1f9523e5

charts/kubedb-catalog/crds/catalog.kubedb.com_cassandraversions.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_mssqlserverautoscalers.yaml, charts/kubedb-crds/crds/autoscaling.kubedb.com_solrautoscalers.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_cassandraversions.yaml, charts/kubedb-crds/crds/kubedb.com_cassandras.yaml, charts/kubedb-crds/crds/kubedb.com_druids.yaml, charts/kubedb-crds/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-crds/crds/kubedb.com_etcds.yaml, charts/kubedb-crds/crds/kubedb.com_mariadbs.yaml, charts/kubedb-crds/crds/kubedb.com_mongodbs.yaml, charts/kubedb-crds/crds/kubedb.com_mssqlservers.yaml, charts/kubedb-crds/crds/kubedb.com_mysqls.yaml, charts/kubedb-crds/crds/kubedb.com_perconaxtradbs.yaml, charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-crds/crds/kubedb.com_redises.yaml, charts/kubedb-crds/crds/kubedb.com_singlestores.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@9b860192

charts/kubedb-metrics/templates/pgbouncer/catalog-kubedb-com-pgbouncerversion.yaml, charts/kubedb-metrics/templates/pgbouncer/kubedb-com-pgbouncer.yaml, charts/kubedb-metrics/templates/pgbouncer/ops-kubedb-com-pgbounceropsrequest.yaml
Signed-off-by: Hiranmoy Das Chowdhury <hiranmoy@appscode.com>
=> Add PgBouncer Dashboard

charts/kubedb-crds/crds/kubedb.com_mssqlservers.yaml
=> Update crds for kubedb/apimachinery@12753471

charts/kubedb-crds/crds/kubedb.com_mysqls.yaml
=> Update crds for kubedb/apimachinery@2fa3548e

charts/kubedb-crds/crds/kubedb.com_mssqlservers.yaml, charts/kubedb-crds/crds/ops.kubedb.com_mssqlserveropsrequests.yaml
=> Update crds for kubedb/apimachinery@8cc86086

charts/kubedb-crds/crds/kubedb.com_solrs.yaml
=> Update crds for kubedb/apimachinery@7e38ccb1

charts/kubedb-crds/crds/ops.kubedb.com_pgbounceropsrequests.yaml
=> Update crds for kubedb/apimachinery@624774d1

charts/kubedb-crds/crds/kubedb.com_kafkas.yaml
=> Update crds for kubedb/apimachinery@9ab2b7bd

charts/kubedb-crds/crds/kubedb.com_druids.yaml, charts/kubedb-crds/crds/kubedb.com_rabbitmqs.yaml
=> Update crds for kubedb/apimachinery@fb7e8ddf

charts/kubedb-crds/crds/ops.kubedb.com_mysqlopsrequests.yaml
=> Update crds for kubedb/apimachinery@886ff390

charts/kubedb-crds/crds/archiver.kubedb.com_mariadbarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mongodbarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mssqlserverarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mysqlarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_postgresarchivers.yaml
=> Update crds for kubedb/apimachinery@e677abc2

charts/kubedb-crds/crds/kafka.kubedb.com_restproxies.yaml
=> Update crds for kubedb/apimachinery@a7900520

charts/kubedb-catalog/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-crds/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-crds/crds/kubedb.com_mariadbs.yaml, charts/kubedb-crds/crds/kubedb.com_mongodbs.yaml, charts/kubedb-crds/crds/kubedb.com_mssqlservers.yaml, charts/kubedb-crds/crds/kubedb.com_mysqls.yaml, charts/kubedb-crds/crds/kubedb.com_perconaxtradbs.yaml, charts/kubedb-crds/crds/kubedb.com_pgbouncers.yaml, charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-crds/crds/kubedb.com_redises.yaml, charts/kubedb-crds/crds/ops.kubedb.com_pgbounceropsrequests.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@e5366d52

charts/kubedb-catalog/crds/catalog.kubedb.com_mariadbversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_mariadbversions.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@e37dc985

charts/kubedb-crds/crds/archiver.kubedb.com_mariadbarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mongodbarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mssqlserverarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mysqlarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_postgresarchivers.yaml, charts/kubedb-crds/crds/kubedb.com_druids.yaml, charts/kubedb-crds/crds/kubedb.com_elasticsearches.yaml, charts/kubedb-crds/crds/kubedb.com_etcds.yaml, charts/kubedb-crds/crds/kubedb.com_mariadbs.yaml, charts/kubedb-crds/crds/kubedb.com_mongodbs.yaml, charts/kubedb-crds/crds/kubedb.com_mssqlservers.yaml, charts/kubedb-crds/crds/kubedb.com_mysqls.yaml, charts/kubedb-crds/crds/kubedb.com_perconaxtradbs.yaml, charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-crds/crds/kubedb.com_redises.yaml, charts/kubedb-crds/crds/kubedb.com_singlestores.yaml
=> Update crds for kubedb/apimachinery@f435670c

charts/kubedb-crds/crds/kubedb.com_solrs.yaml
=> Update crds for kubedb/apimachinery@47139029

charts/kubedb-crds/crds/ops.kubedb.com_postgresopsrequests.yaml
=> Update crds for kubedb/apimachinery@a75252a4

charts/kubedb-crds/crds/kubedb.com_ferretdbs.yaml, charts/kubedb-crds/crds/ops.kubedb.com_ferretdbopsrequests.yaml
=> Update crds for kubedb/apimachinery@28f8a1d6

charts/kubedb-crds/crds/kubedb.com_kafkas.yaml
=> Update crds for kubedb/apimachinery@b555d303

charts/kubedb-crds/crds/kubedb.com_clickhouses.yaml
=> Update crds for kubedb/apimachinery@bd55299c

charts/kubedb-crds/crds/kubedb.com_ignites.yaml
=> Update crds for kubedb/apimachinery@6dba2e99

charts/kubedb-crds/crds/ops.kubedb.com_cassandraopsrequests.yaml
=> Update crds for kubedb/apimachinery@02cb3e12

charts/kubedb-catalog/crds/catalog.kubedb.com_hazelcastversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_oracleversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_hazelcastversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_oracleversions.yaml, charts/kubedb-crds/crds/kubedb.com_hazelcasts.yaml, charts/kubedb-crds/crds/kubedb.com_oracles.yaml, charts/kubedb-crds/crds/ops.kubedb.com_hazelcastopsrequests.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@e9f8caba

charts/kubedb-crds/crds/kubedb.com_cassandras.yaml, charts/kubedb-crds/crds/ops.kubedb.com_cassandraopsrequests.yaml
=> Update crds for kubedb/apimachinery@2f14197a

charts/kubedb-crds/crds/kubedb.com_clickhouses.yaml, charts/kubedb-crds/crds/kubedb.com_ignites.yaml, charts/kubedb-crds/crds/ops.kubedb.com_hazelcastopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_igniteopsrequests.yaml
=> Update crds for kubedb/apimachinery@68c02c68

charts/kubedb-crds/crds/archiver.kubedb.com_mariadbarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mongodbarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mssqlserverarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mysqlarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_postgresarchivers.yaml
=> Update crds for kubedb/apimachinery@07b6689c

charts/kubedb-crds/crds/autoscaling.kubedb.com_hazelcastautoscalers.yaml, charts/kubedb-crds/crds/gitops.kubedb.com_mariadbs.yaml, charts/kubedb-crds/crds/gitops.kubedb.com_postgreses.yaml, charts/kubedb-crds/crds/kubedb.com_mariadbs.yaml, charts/kubedb-crds/crds/kubedb.com_postgreses.yaml, charts/kubedb-crds/crds/ops.kubedb.com_cassandraopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_clickhouseopsrequests.yaml, charts/kubedb-crds/crds/ops.kubedb.com_redisopsrequests.yaml
=> Update crds for kubedb/apimachinery@6888d138

charts/kubedb-crds/crds/archiver.kubedb.com_mariadbarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mongodbarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mssqlserverarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_mysqlarchivers.yaml, charts/kubedb-crds/crds/archiver.kubedb.com_postgresarchivers.yaml
=> Update crds for kubedb/apimachinery@ed84b233

charts/kubedb-grafana-dashboards/dashboards/postgres/postgres_databases_dashboard.json
=> Postgres: Grafana Dashboard panel for Replication Slot lag

charts/kubedb-crds/crds/autoscaling.kubedb.com_igniteautoscalers.yaml, charts/kubedb-crds/crds/ops.kubedb.com_clickhouseopsrequests.yaml
=> Update crds for kubedb/apimachinery@f56c4f01

charts/kubedb-crds/crds/kubedb.com_clickhouses.yaml, charts/kubedb-crds/crds/ops.kubedb.com_clickhouseopsrequests.yaml
=> Update crds for kubedb/apimachinery@dc61a043

charts/kubedb-catalog/crds/catalog.kubedb.com_pgbouncerversions.yaml, charts/kubedb-catalog/crds/catalog.kubedb.com_pgpoolversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_pgbouncerversions.yaml, charts/kubedb-crds/crds/catalog.kubedb.com_pgpoolversions.yaml, charts/kubedb-crds/crds/gitops.kubedb.com_pgbouncers.yaml, charts/kubedb-crds/crds/gitops.kubedb.com_pgpools.yaml, charts/kubedb-crds/crds/kubedb.com_pgbouncers.yaml, charts/kubedb-crds/crds/kubedb.com_pgpools.yaml, crds/kubedb-catalog-crds.yaml
=> Update crds for kubedb/apimachinery@b8bdbe2c
