deploy/kubedb.sh

`detect_tag` function is removed in earlier PR. https://github.com/kubedb/installer/pull/2/files#diff-6c05da76313699c3dab3dae1679675b7L50
`CUSTOM_OPERATOR_TAG` has no need/purpose now. Developers can set `KUBEDB_OPERATOR_TAG`.

Remove detect_tag function call

---

chart/kubedb/templates/deployment.yaml
chart/kubedb/templates/service.yaml
chart/kubedb/values.yaml

Should fix https://github.com/kubedb/project/issues/577
In my case, the problem is that the master cannot communicate with the kubelet on port `8443` presumably because of the default GKE firewall rules that come when VPC Native IPs are enabled. 
By changing the api port to `443` kubedb now works for me. 
I think 443 should be the default since 8443 is a nonstandard port, however, I left the default as 8443 in case it breaks something I'm not aware of.

Allow apiserver port change

---

chart/kubedb-catalog/templates/mongodb.yaml
deploy/kubedb-catalog/mongodb.yaml

`mongo` and `mongo-tools` shared tags:
- 3.4.17
- 3.4.22 => 3.4-v4
- 3.6.8
- 3.6.13 => 3.6-v4
- 4.0.3
- 4.0.5-v2
- 4.0.11 => 4.0-v2
- 4.1.4
- 4.1.7-v2
- 4.1.13 => 4.1
Here, Pre-SSPL (before October 16, 2018) versions:
- 3.4.17
- 3.6.8
- 4.0.3
- 4.1.4
Fixes https://github.com/kubedb/project/issues/614

Support more Mongodb versions

---

chart/kubedb/templates/cleaner.yaml

When installing kubedb in a namespace other than `default`, the Job will never get executed and fails to create with 
> Error creating: pods "kubedb-operator-cleaner-" is forbidden: error looking up service account default/kubedb-operator: serviceaccount "kubedb-operator" not found

Add namespace to cleaner Job

---

charts/kubedb/templates/cluster-role.yaml
deploy/rbac-list.yaml

Changed by mistake in https://github.com/kubedb/installer/commit/b24b05e18c7fc59cab4a9da126f7631acb3c9452#diff-148edb39f7cfdfba7fdda1069bd3e762L136

Fix RBAC permissions for Stash restoresessions

---

charts/kubedb/templates/deployment.yaml

Hi,
If we both use `criticalAddon: true` and
`tolerations: {...}`, generated yaml is not correct.
This PR adds correct indentation for critical addons toleration

Fix tolerations indentation for deployment

---

charts/kubedb/templates/appcatalog-user-roles.yaml
charts/kubedb/templates/mutating-webhook.yaml
charts/kubedb/templates/user-roles.yaml
charts/kubedb/templates/validating-webhook.yaml

Signed-off-by: Arthur Outhenin-Chalandre <arthur@cri.epita.fr>
This PR removes the post-install hook on some cluster roles. I see no reason to have these hooks in the first place (but maybe there is one?). It also fixes this issue https://github.com/kubedb/issues/issues/522.

Fix helm install --wait flag

---

charts/kubedb-catalog/templates/memcached.yaml

The newer release is needed for PMEM and probably also various bug
fixes.
Related-to: https://github.com/kubedb/issues/issues/690
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>

memcached: add 1.5.22

---

charts/kubedb-catalog/templates/mysql/mysql-5.7.25.yaml
charts/kubedb-catalog/templates/mysql/mysql-5.7.29.yaml
charts/kubedb-catalog/templates/mysql/mysql-5.7.yaml
charts/kubedb-catalog/templates/mysql/mysql-5.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.14.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.18.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.19.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.20.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.3.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.yaml

Downgrade from MySQL 8.0 to MySQL 5.7, or from a MySQL 8.0 release to a previous MySQL 8.0 release, is not supported.
ref: https://dev.mysql.com/doc/refman/8.0/en/downgrading.html
Signed-off-by: suaas21 <sagor@appscode.com>

Add MySQL new Version

---

charts/kubedb-catalog/Chart.yaml
charts/kubedb-catalog/README.md
charts/kubedb-catalog/doc.yaml
charts/kubedb/Chart.yaml
charts/kubedb/README.md
charts/kubedb/doc.yaml
charts/kubedb/values.yaml

ProductLine: KubeDB
Release: v2020.07.10-beta.1
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/3

Prepare for release v0.14.0-beta.1

---

charts/kubedb-enterprise/templates/deployment.yaml

/tmp directory is used to hold certificates & private keys

Mount emptyDir as /tmp for enterprise operator

---

charts/kubedb/templates/cluster-role.yaml

Add `restorbatch` role under `stash` for `kubedb`
Signed-off-by: anis028 <anis028@appscode.com>

Change cluster-role of kubedb for stash/restorebatch

---

charts/kubedb-catalog/Chart.yaml
charts/kubedb-catalog/README.md
charts/kubedb-catalog/doc.yaml
charts/kubedb-catalog/templates/mysql/deprecated-mysql-5.7.yaml
charts/kubedb-catalog/templates/mysql/deprecated-mysql-5.yaml
charts/kubedb-catalog/templates/mysql/deprecated-mysql-8.0.yaml
charts/kubedb-catalog/templates/mysql/deprecated-mysql-8.yaml
charts/kubedb-catalog/templates/mysql/mysql-5.7.25.yaml
charts/kubedb-catalog/templates/mysql/mysql-5.7.29.yaml
charts/kubedb-catalog/templates/mysql/mysql-5.7.31.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.14.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.20.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.21.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.3.yaml
charts/kubedb/Chart.yaml
charts/kubedb/README.md
charts/kubedb/doc.yaml
charts/kubedb/values.yaml

ProductLine: KubeDB
Release: v2020.10.27-rc.0
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/17

Prepare for release v0.14.0-beta.6

---

charts/kubedb-catalog/templates/elasticsearch/1.0.2-opendistro.yaml
charts/kubedb-catalog/templates/elasticsearch/1.1.0-opendistro.yaml
charts/kubedb-catalog/templates/elasticsearch/1.2.1-opendistro.yaml
charts/kubedb-catalog/templates/elasticsearch/1.3.0-opendistro.yaml
charts/kubedb-catalog/templates/elasticsearch/1.4.0-opendistro.yaml
charts/kubedb-catalog/templates/elasticsearch/1.6.0-opendistro.yaml
charts/kubedb-catalog/templates/elasticsearch/1.7.0-opendistro.yaml
charts/kubedb-catalog/templates/elasticsearch/1.8.0-opendistro.yaml
charts/kubedb-catalog/templates/elasticsearch/1.9.0-opendistro.yaml

Ref:
- https://opendistro.github.io/for-elasticsearch-docs/version-history/

Use original underlying Elasticsearch version in openDistro version crds 

---

charts/kubedb-enterprise/templates/cluster-role.yaml

We need to delete the StatefulSet's PVC while horizontally scaling down the DB nodes.

Add permission to delete PVC for enterprise operator

---

charts/kubedb-autoscaler/templates/cluster-role.yaml
charts/kubedb-enterprise/templates/cluster-role.yaml
charts/kubedb/templates/cluster-role.yaml

xref: https://sdk.operatorframework.io/docs/faqs/#i-keep-hitting-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-how-do-i-fix-this

Add permission to add finalizers on custom resoures

---

charts/kubedb-catalog/templates/mysql/mysql-5.7.25.yaml
charts/kubedb-catalog/templates/mysql/mysql-5.7.29.yaml
charts/kubedb-catalog/templates/mysql/mysql-5.7.31.yaml
charts/kubedb-catalog/templates/mysql/mysql-5.7.33.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.14.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.20.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.21.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.23.yaml
charts/kubedb-catalog/templates/mysql/mysql-8.0.3.yaml

1. Added/Updated MySQL catalogs:
- 8.0.23 
- 5.7.33
- 8.0.21, 8.0.20, 8.0.14, 8.0.3
- 5.7.31, 5.7.29, 5.7.25
2. Used `kubedb/toybox:0.8.4` instead of `kubedb/busybox`
Signed-off-by: suaas21 <sagor@appscode.com>

Update MySQL catalogs

---

charts/kubedb-community/templates/validating-webhook.yaml

When the license expires, the operator pod goes into a crashloop. This change ensures that users can delete namespaces even though the namespace validator is not running.

Don't fail deleting namespace when license expires

---

apis/installer/v1alpha1/kubedb_catalog_types.go
charts/kubedb-catalog/README.md
charts/kubedb-catalog/templates/_helpers.tpl
charts/kubedb-catalog/templates/mongodb/mongodb-3.6.18-percona.yaml
charts/kubedb-catalog/templates/mongodb/mongodb-4.0.10-percona.yaml
charts/kubedb-catalog/templates/mongodb/mongodb-4.2.7-percona.yaml
charts/kubedb-catalog/templates/postgres/postgres-10.16-postgresql.yaml
charts/kubedb-catalog/templates/postgres/postgres-11.11-postgresql.yaml
charts/kubedb-catalog/templates/postgres/postgres-11.11-timescaledb.yaml
charts/kubedb-catalog/templates/postgres/postgres-12.6-postgresql.yaml
charts/kubedb-catalog/templates/postgres/postgres-12.6-timescaledb.yaml
charts/kubedb-catalog/templates/postgres/postgres-13.2-postgresql.yaml
charts/kubedb-catalog/templates/postgres/postgres-13.2-timescaledb.yaml
charts/kubedb-catalog/templates/postgres/postgres-9.6.21-postgresql.yaml
charts/kubedb-catalog/values.openapiv3_schema.yaml
charts/kubedb-catalog/values.yaml
charts/kubedb/templates/_helpers.tpl
charts/kubedb/values.openapiv3_schema.yaml
crds/installer.kubedb.com_kubedbcatalogs.yaml
crds/installer.kubedb.com_kubedbs.yaml
hack/fmt/main.go
hack/fmt/main_test.go

Example:
```bash
$ helm template charts/kubedb-catalog --set image.registry=tamal --set image.overrideOfficialRegistry=true | grep postgres:
$ helm template charts/kubedb --set global.registry=tamal --set kubedb-catalog.image.overrideOfficialRegistry=true | grep postgres:
```

Allow overriding official registry in catalog

---

charts/kubedb-community/templates/cluster-role.yaml

ref:
- https://github.com/kmodules/monitoring-agent-api/blob/1953ad20c8084741a62e17ba8bdcbde281d82860/agents/prometheusoperator/lib.go#L82
- https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-

Add permission to set finalizers on services

---

charts/kubedb-metrics/templates/elasticsearch/catalog-kubedb-com-elasticsearchversion.yaml
charts/kubedb-metrics/templates/mariadb/catalog-kubedb-com-mariadbversion.yaml
charts/kubedb-metrics/templates/mariadb/ops-kubedb-com-mariadbopsrequest.yaml
charts/kubedb-metrics/templates/mongodb/catalog-kubedb-com-mongodbversion.yaml
charts/kubedb-metrics/templates/mongodb/ops-kubedb-com-mongodbopsrequest.yaml
charts/kubedb-metrics/templates/mysql/catalog-kubedb-com-mysqlversion.yaml
charts/kubedb-metrics/templates/mysql/ops-kubedb-com-mysqlopsrequest.yaml
charts/kubedb-metrics/templates/postgres/catalog-kubedb-com-postgresversion.yaml
charts/kubedb-metrics/templates/postgres/ops-kubedb-com-postgresopsrequest.yaml
charts/kubedb-metrics/templates/redis/catalog-kubedb-com-redisversion.yaml
charts/kubedb-metrics/templates/redis/ops-kubedb-com-redisopsrequest.yaml

This is done to match the new panopticon metrics naming format

Remove kind from metric name prefix
